### ISSUE TITLE
un document transcrit pour lequel rien ne s'affiche dans la v2 (ni son ni transcription)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#10]
Histoire de Kautjajuk (langue : inuktitut)

DOI de l'annotation : https://doi.org/10.24397/pangloss-0005711 

(juste pour mémoire : DOI du son : doi:10.24397/pangloss-0005710 )

Adresse dans la v2 : ...corpus/show?oai_primary=cocoon-a84baa2b-f874-474c-9715-ff8810ed3a07&oai_secondary=cocoon-15ae76de-1694-4eb4-9057-a13c35902fed

Affichage dans la v1 :
https://pangloss.cnrs.fr/corpus/show_text.php?id=cocoon-a84baa2b-f874-474c-9715-ff8810ed3a07&idref=cocoon-15ae76de-1694-4eb4-9057-a13c35902fed

Est-ce à cause des attributs 'non standard' des transcriptions ? 
Transcription par phrase
 **Syllabique
 Romanisée
 Segmentée en morphèmes**

![image](https://user-images.githubusercontent.com/6072524/96504326-cd8c2a00-1254-11eb-85a2-de63f2ace63c.png)

**Comment by alexis-michaud** [comment]
@sguillaume confirmera : on peut mettre les attributs qu'on veut pour les transcriptions, n'est-ce pas ? les déclarer comme `kindOf="phonetic" `mais aussi bien `kindOf="phonétique", kindOf="transcription romanisée approximative"`... Bref ce n'est pas un vocabulaire contrôlé, je crois bien. Il faut être prêt à diverses valeurs.

**Comment by m8nli9ht** [comment]
Traité. Sera visible au prochain build intégré par Edouard.
