### ISSUE TITLE
lien vers section en 3e langue : le clic n'atteint pas son objectif quand la page est très longue

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#11]
Le site v2 permet d'avoir un texte dans une 3e langue, par exemple le russe pour des langues parlées en Russie, le chinois pour la Chine, etc. 

Ca fonctionne actuellement pour le na de Yongning (_yongning na_). On peut cliquer même quand la partie "Continuer la lecture/See more" n'est pas encore déroulée. 

Pour le naxi, *en version anglaise*, le lien a été créé : en haut à droite sur l'image ci-dessous.
![image](https://user-images.githubusercontent.com/6072524/96682562-484e6580-1379-11eb-861f-364e970e896d.png)

Mais quand on n'a pas préalablement ouvert quand la partie "See more", le clic n'aboutit pas à ouvrir cette page. Il amène simplement en haut de la liste des ressources, comme reproduit ci-dessous :
![image](https://user-images.githubusercontent.com/6072524/96682706-80ee3f00-1379-11eb-8abb-d347db8049c6.png)

Est-ce parce que la page est très longue ? 

(il s'agit d'accéder à corpus/Naxi?lang=en#%E4%B8%AD%E6%96%87%E4%BB%8B%E7%BB%8D )

Quand on a préalablement ouvert la partie "See more", ça marche ! On parvient à l'affichage reproduit ci-dessous : 
![image](https://user-images.githubusercontent.com/6072524/96682975-d9254100-1379-11eb-922b-b10941fca131.png)

Si on veut 'finasser', il y aurait un tout petit ajustement vertical à faire : le bandeau en tête de page cache les 3 premières lignes de la section en chinois (le titre & les 2 lignes qui suivent). Il faudrait donc, si possible, aligner le haut du texte affiché **un peu plus haut**, de façon à obtenir un affichage disons à peu près comme ci-dessous : 

![image](https://user-images.githubusercontent.com/6072524/96683164-14277480-137a-11eb-8ec9-0fb3a2675424.png)

Je ne sais pas si c'est clair...?

Une possibilité, si c'est une question de dimension de la page, ce serait d'indiquer aux 'éditeurs' de la page de limiter à telle ou telle taille. Ca pourrait être raisonnable que les pages ne prennent pas des dimensions déraisonnables. (La page naxi est un peu excessive... Il y a des trucs dessus qui auraient vocation à aller sur un blog plutôt que sur cette page)

Merci beaucoup ! 
@Doudou-git

**Comment by EdouardSombie** [comment]
Salut Alexis,

C'est bizarre… sur la page Yongning na, la section "see more" s'ouvre bien.
Je vais regarder d'où vient le problème.

A tout à l'heure
Edouard

**Comment by alexis-michaud** [comment]
C'est la page qui est trop chargée. Il y a beaucoup de bazar dans le HTML de la page naxi, pas encore finie. Il vaudrait peut-être mieux que je commence par du ménage ? 

J'ai élagué en virant (à titre de test) presque toute la partie qui précède le chinois... et là ça remarche.

**Comment by alexis-michaud** [comment]
(tu peux aller voir là maintenant tout de suite)

**Comment by alexis-michaud** [comment]
Il doit y avoir soit un seuil de complexité (quantité de texte, d'images...), soit un truc dans le HTML de cette page en particulier qui faisait planter.

**Comment by alexis-michaud** [comment]
Le fichier long (complet, récupéré de l'ancien site, en cours de modif) est ici : 
https://www.dropbox.com/s/s52yazftppd5zzd/naxi_en_suite.html?dl=0

**Comment by EdouardSombie** [comment]
En fait, il y a dans le contenu du texte des liens hypertexte relatifs qui font planter le javascript.
Ex : ../corpus/show_text_en.php?id=cocoon-33ea5cf5-9051-347f-90eb-80a7eca0b94b&idref=cocoon-60e729e2-17b4-3101-acae-f55e360f1bcc
J'ai fait en sorte qu'ils ne perturbent plus le script.
Pour pouvoir les identifier, ils apparaissent maintenant surlignés en jaune.
A ce titre, j'ai remis le texte anglais pour que tu vois le ménage à faire.

**Comment by EdouardSombie** [comment]
Pour ce qui est de la finasserie, le titre appelé n'est plus caché par la barre de navigation.
Je te laisse constater par toi-même.
![Capture d’écran 2020-10-24 à 11 44 16](https://user-images.githubusercontent.com/66474742/97078721-4b9e5700-15ee-11eb-947a-622b711fb93c.png)

**Comment by alexis-michaud** [comment]
Le ménage pour la page 'naxi' en anglais est fait : les liens "à l'ancienne" ont été remplacés par des [DOI](https://halshs.archives-ouvertes.fr/halshs-02870206/).
