### ISSUE TITLE
"bug du carré blanc" pour affichage de manuscrits

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#13]
show?oai_primary=cocoon-0d9175f1-3110-3b86-88ee-abc1ca33b096&oai_secondary=cocoon-ea167a26-448c-3ac3-8a66-c4faf8c18b71
La boîte qui met en valeur la partie du texte qu'on entend entre dans une zone "blanche" : souci d'alignement entre la boîte et le texte

**Comment by alexis-michaud** [comment]
réponse de @m8nli9ht (je recopie) : 

Concernant le manuscrit Lai Pao, le problème ne se présente pas chez moi, peut-être me préciser sur quel device et avec quelle résolution le bug est apparu.
![image](https://user-images.githubusercontent.com/6407776/96362575-a0455c00-112e-11eb-8652-f2ff483d7efd.png)

**Comment by alexis-michaud** [comment]
alors je suis en : 1920 x 1200 pixels
diagonale d'affichage : 23.6"
dimensions (largeur x hauteur) : 20 x 12.5

Chrome 86.0.4240.75 (64-bit)

Windows 10

Pour indiquer où on "quitte la route" : c'est sur le mot baːw⁴
![image](https://user-images.githubusercontent.com/6072524/96369287-49a14780-1159-11eb-902b-6b877e168483.png)
On est sur la 1e phrase.

**Comment by alexis-michaud** [comment]
C'est sans doute un problème de défilement horizontal ? Il semble que la taille dévolue à l'image soit exactement *double* de sa taille réelle.
![image](https://user-images.githubusercontent.com/6072524/96409093-07bde300-11e5-11eb-967e-d142268becf5.png)

D'ailleurs, est-il indispensable d'avoir un ... je ne sais pas comment ça s'appelle : une barre de défilement sous l'image, pour se déplacer de gauche à droite ? pareil pour le mouvement vertical ? Les bandes de manuscrits étant "prédécoupées" pour affichage, c'est dommage de devoir se déplacer. Ce serait super si on pouvait voir les "bandes" de manuscrit en entier sans se déplacer verticalement ni horizontalement.

**Comment by m8nli9ht** [comment]
A priori je dirais que c'est un pb côté intégration : une instruction CSS sur les img (max-width : 100% !important dans le main.css du dist) 
![image](https://user-images.githubusercontent.com/6407776/102497427-ed837280-4078-11eb-9627-a7535f70728d.png)

**Comment by EdouardSombie** [comment]
Salut,
Le pb ne vient pas de max-width ou max-height. Les désactiver ne change rien.
Le pb vient du fait que l'img a une width de 762px. C'est ça qui la fait déborder du conteneur.
Est-ce que tu peux utiliser une largeur en % plutôt ?
Si tu es obligé d'utiliser une valeur en px, je crois qu'on sera obligé de faire un scale (que je préfèrerai éviter...)

A tout à l'heure

**Comment by m8nli9ht** [comment]
Ok, je regarde comment je peux gérer mais à priori je ne vois pas comment ne pas utiliser le scale car il n'y a pas que l'image mais tous les <canvas> qui permettent d'encadrer les mots en live.

**Comment by alexis-michaud** [comment]
Toujours un souci, sur mon poste informatique. Seule la moitié gauche de chaque "bande" du manuscrit s'affiche. 

Exemple [ici](https://pangloss.cnrs.fr/v2/corpus/show?lang=fr&oai_primary=cocoon-0d9175f1-3110-3b86-88ee-abc1ca33b096&oai_secondary=cocoon-ea167a26-448c-3ac3-8a66-c4faf8c18b71).

Il n'y a plus de bande de défilement, donc plus de souci avec la bande de défilement... mais l'image est 'tronquée'.

![image](https://user-images.githubusercontent.com/6072524/103354394-b450f680-4aab-11eb-9ead-ebe3f48c7108.png)

**Comment by m8nli9ht** [comment]
Désolé je ne peux rien (à moins d'avoir une instruction de Edouard à appliquer), encore une fois, de mon côté je n'ai pas ce bug :
![image](https://user-images.githubusercontent.com/6407776/103355044-853b8480-4aad-11eb-8848-aa33f8999884.png)

**Comment by alexis-michaud** [comment]
OK on confirme que la balle est dans le camp de @EdouardSombie !

**Comment by EdouardSombie** [comment]
Du coup, vous voulez que je fasse un scale pour réduire la taille des images ?
Je vais le faire, mais je ne suis pas sûr qu'on obtienne un résultat homogène vu que les images n'ont pas toutes les mêmes dimensions. Je vais me basé sur l'exemple que donne Alexis.

**Comment by alexis-michaud** [comment]
"Du coup, vous voulez que je fasse un scale pour réduire la taille des images ?
Je vais le faire, mais je ne suis pas sûr qu'on obtienne un résultat homogène vu que les images n'ont pas toutes les mêmes dimensions."

En effet, réduire l'échelle des images de façon _ad hoc_ pour faire rentrer dans le cadre, ça serait moche et nuirait à la lecture. C'est important de **garder la même échelle** pour chacune des "bandes" découpées à l'intérieur des manuscrits. Si on fait un "scale", il faut faire le même pour toutes les bandes.

Je pense que c'est ça qu'il faut faire pour l'instant. De toute façon, pour les manuscrits, il y a toutes sortes d'autres questions qui vont se poser pour le traitement de documents divers : écritures verticales, écritures courbes... Toutes sortes de défis et de complications. 

Pour lancer tout de même une idée, pour le cas où cette réduction de toutes les bandes nuirait vraiment beaucoup à leur bonne lisibilité (taille trop petite) : est-ce qu'il n'y aurait pas un moyen de laisser l'image déborder du cadre (relativement étroit) dévolu au lecteur Eastling au sein de l'écran ? 

Actuellement, sur un grand écran (=normalement, l'optimal qu'on souhaite, pour afficher un document iconographique scanné avec tout son appareil critique), moins de la moitié de la largeur d'écran est utilisée pour afficher le manuscrit en mode image.  
![image](https://user-images.githubusercontent.com/6072524/103414057-93a4a180-4b7c-11eb-84b4-48f48abd7065.png)

Serait-il imaginable d'avoir une largeur d'image disons de 30% plus élevée qu'actuellement ? 

Montage-exemple (barbare) ci-dessous : on 'mord' dans la marge gauche (élargissement de la colonne consacrée à Eastling) de façon à pouvoir afficher une image plus large. 
![image](https://user-images.githubusercontent.com/6072524/103414267-92c03f80-4b7d-11eb-8d14-ea04bd81da74.png)

**Comment by alexis-michaud** [comment]
Le mode "pleine largeur" désormais mis en place résoud cette difficulté
