### ISSUE TITLE
fichiers électroglottographiques : ce ne sont pas des annotations

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#14]
Un fichier électroglottographique, c'est un signal WAV de format identique à l'audio, mais de contenu différent (signal enregistré en faisant passer un courant de très basse intensité et de très haute fréquence entre 2 électrodes posées de part et d'autre du larynx). 

Dans la version actuelle du lecteur Eastling (27 octobre), ça s'affiche comme une annotation

![image](https://user-images.githubusercontent.com/6072524/97356821-1ff2c980-1899-11eb-8077-9967ca7c8620.png)

(et du coup la page est en blanc)

C'est un fichier qu'on peut télécharger : il n'y a pas lieu d'en donner un affichage particulier en ligne. Les gens que ça intéresse téléchargent le fichier et l'analysent avec l'outil de leur choix, par exemple les outils du dépôt [Covarep](https://github.com/covarep/covarep).

**Comment by m8nli9ht** [comment]
Peux-tu me dire avec quel document tu as fait ce test ? (ID primary et secondary)

**Comment by alexis-michaud** [comment]
oai_primary=cocoon-b3b0112a-e6bb-3ea7-b2f8-9d838aa172e2
&oai_secondary=cocoon-390794f4-15ff-3a78-8bcf-9580614ff98e

&optionGlosses=&optionNotes=true&optionTranscriptions=&optionTranslations=&optionWholeTranscriptions=false&optionWholeTranslations=&optionWords=false

**Comment by m8nli9ht** [comment]
c'est un ticket pour Edouard car à aucun moment je ne récupère ce fichier depuis le player
