### ISSUE TITLE
malentendu concernant le bouton "Notes" ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#15]
Concernant le bouton "Notes" : actuellement, quand on utilise ce bouton, ce qui apparaît, ce ne sont pas les notes du texte (élément \<NOTE\> du document XML contenus à l'intérieur des éléments phrase, \<S\>), mais les notes situées au niveau du texte entier. 

![image](https://user-images.githubusercontent.com/6072524/97357403-01410280-189a-11eb-96fd-7d6d11085a55.png)

Ce qui devrait s'afficher (et disparaître quand on décoche), ce sont **tous** les éléments \<NOTE\> : contenus à l'intérieur des éléments phrase, \<S\> (notes qu'il faut en outre distinguer par langue : fr, en, etc) et aussi, pourquoi pas, les notes situées au niveau du texte entier (qui peuvent s'afficher en tête).

Quant aux éléments NOTE qui se rapportent aux niveaux W et M (mot et morphème) : il n'y a pas pour l'instant de solution précise pour les afficher. L'idéal serait un système d'appel de notes pour chacune de ces notes, qui permettrait un lien clair et non ambigu entre le mot (ou le morphème) et la note. A discuter (ce serait une amélioration notable du lecteur).

**Comment by m8nli9ht** [comment]
Peux-tu me dire avec quel document tu as fait ce test ?

**Comment by alexis-michaud** [comment]
Le même que pour #14 :

oai_primary=cocoon-b3b0112a-e6bb-3ea7-b2f8-9d838aa172e2 
&oai_secondary=cocoon-390794f4-15ff-3a78-8bcf-9580614ff98e

&optionGlosses=&optionNotes=true&optionTranscriptions=&optionTranslations=&optionWholeTranscriptions=false&optionWholeTranslations=&optionWords=false

**Comment by m8nli9ht** [comment]
OK. Du coup il faut proposer l'option NOTE comme pour les GLOSSES (cases à cocher pour les langues disponibles).
Doit-on conserver ou supprimer les notes au niveau du texte entier ?

**Comment by m8nli9ht** [comment]
Traité (sera visible sur Pangloss test lors de la prochaine livraison de build à Edouard)

**Comment by alexis-michaud** [comment]
Ticket fermé. Reste la poursuite du développement pour les notes : 

> L'idéal serait un système d'appel de notes pour chacune de ces notes, qui permettrait un lien clair et non ambigu entre le mot (ou le morphème) et la note. A discuter (ce serait une amélioration notable du lecteur).

Les échanges au sujet de ce développement-là se poursuivent dans un autre ticket : #17
