### ISSUE TITLE
affichage des notes

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#17]
La DTD permet d'ajouter des notes à chacun des niveaux : 
au niveau du texte entier, de la phrase, du mot, du morphème... 

Pour les listes de mots aussi bien que pour les textes. 

Ce serait super d'afficher toutes les notes, en bon ordre. Chacune avec un appel de note en utilisant les symboles Unicode des chiffres cerclés. Ca va jusqu'à 20... et ça repart ensuite jusqu'à 35... puis jusqu'à 50 ! Comme les 
https://www.compart.com/fr/unicode/decomposition/%3Ccircle%3E

L'appel de note serait situé à droite du contenu (FORM) du niveau concerné. 
On redémarrerait la notation pour chaque phrase. (Pour un texte entier, il pourrait y avoir plus de 50 notes en tout ; pour une seule phrase, ce serait vraiment une mauvaise idée d'aller jusqu'à 50 notes, et on peut en faire une limite 'en dur' pour l'affichage.)

On afficherait d'abord les notes qui se rapportent au niveau de la phrase entière, puis les notes se rapportant aux mots, puis les notes se rapportant aux morphèmes. 

Notes au niveau du texte : on les laisse là où elles s'affichent actuellement = sous le titre (en début, avant la phrase 1).

**Comment by alexis-michaud** [comment]
Voici un exemple artificiellement élaboré à partir de la phrase 2 d'[un texte na](https://doi.org/10.24397/pangloss-0004345) qui comporte deux notes au niveau de la phrase (`<S>`), notes auxquelles on ajoute, pour le propos de l'exemple, une 3e note concernant le premier mot (`<W>`).

 (Identifiant du document sur le nouveau site : `corpus/show?lang=en&oai_primary=cocoon-9245e7d0-3e19-3eac-8f3e-2dc3a04bbf43&oai_secondary=cocoon-b5285065-cb88-3de1-b3d6-9cab013681f7`)

> ɖɯ˧-ʑi˩-ɻ̍˩-dʑo˩ | tʰi˩˥, | <mmm…> ʈʂʰɯ˧ne˧-ʝi˥ | pi˧-ɲi˥-tsɯ˩ ◊ -mv̩˩, | æ˧ʂæ˧qʰwɤ˧-ʈʂʰɯ˥-dʑo˩, ◊ ə˩-gi˩! | ① ② 
> ɖɯ˧˥③ ʑi˧˥ =ɻ̍˩ _(etc.)_
> 1 °clf.familles °associatif _(etc.)_
> (il y avait) une famille, eh bien… c’est comme ça qu’on raconte, (dans) cette histoire, n’est-ce pas!
> 有一家人……是这样讲的，这个故事，是吧？
> ① le ton de «histoire» se déploie sur le démonstratif.
> ② d’abord noté /‡pi˩ ɲi˧/; en fait: est le début d’un mot phonologique: /pi˧ ɲi˥/. Sens: vérifié: est la copule, dans son emploi grammaticalisé servant à renforcer l'affirmation; ce n'est pas le verbe «vouloir, avoir besoin de».
> ③ le ton du numéral connaît une modification inattendue dans ce contexte, blablabla

**Comment by m8nli9ht** [comment]
Vu pendant la visio du 20/11/2020 (Alexis, Edouard) : il faut créer un composant React "NOTE" qui interagisse avec les composants Sentence ou Word associé selon qu'on soit en mode TEXT ou WORDLIST

**Comment by m8nli9ht** [comment]
> oai_primary=cocoon-9245e7d0-3e19-3eac-8f3e-2dc3a04bbf43&oai_secondary=cocoon-b5285065-cb88-3de1-b3d6-9cab013681f7

Il me faudrait un exemple de document avec ce cas de niveau de notes afin de développer correctement le composant, une idée ?

**Comment by alexis-michaud** [comment]
Oui, un exemple fictif ne suffit pas, il faut un vrai exemple pour que ça puisse être interrogé via Cocoon. 

Pour l'instant, les exemples manquent : comme les notes n'étaient affichées qu'au niveau de la phrase, les utilisateurs n'en mettaient guère au niveau du mot. 

Je viens de faire une mise à jour d'un texte na : REWARD, en déplaçant une note du niveau `<S>` au niveau `<W>`. C'est dans la phrase 154.

```
<W>
			<FORM>ʈʰæ˧mi˧-ɳɯ˩</FORM>
			<NOTE xml:lang="fr" message="ʈʰææ̃˧ / ʈʰæ˧mi˧-ɳɯ˩: initiale réalisée proche de [ʈʂʰ]"></NOTE>
			<TRANSL xml:lang="fr">vraiment</TRANSL>
</W>

```

Maintenant il est nécessaire que @sguillaume fasse la mise à jour de ce document dans Cocoon. 

Lien de la mise à jour dans le dépôt GitHub des données na :
https://github.com/alexis-michaud/na/commit/caf1c92f8db936f7d1537064cb98328f434534a2

Lien direct vers le texte :  
https://github.com/alexis-michaud/na/blob/master/TEXT/F4/crdo-NRU_F4_REWARD.xml

**Comment by m8nli9ht** [comment]
> 
> 
> Voici un exemple artificiellement élaboré à partir de la phrase 2 d'[un texte na](https://doi.org/10.24397/pangloss-0004345) qui comporte deux notes au niveau de la phrase (`<S>`), notes auxquelles on ajoute, pour le propos de l'exemple, une 3e note concernant le premier mot (`<W>`).
> 
> (Identifiant du document sur le nouveau site : `corpus/show?lang=en&oai_primary=cocoon-9245e7d0-3e19-3eac-8f3e-2dc3a04bbf43&oai_secondary=cocoon-b5285065-cb88-3de1-b3d6-9cab013681f7`)
> 
> > ɖɯ˧-ʑi˩-ɻ̍˩-dʑo˩ | tʰi˩˥, | <mmm…> ʈʂʰɯ˧ne˧-ʝi˥ | pi˧-ɲi˥-tsɯ˩ ◊ -mv̩˩, | æ˧ʂæ˧qʰwɤ˧-ʈʂʰɯ˥-dʑo˩, ◊ ə˩-gi˩! | ① ②
> > ɖɯ˧˥③ ʑi˧˥ =ɻ̍˩ _(etc.)_
> > 1 °clf.familles °associatif _(etc.)_
> > (il y avait) une famille, eh bien… c’est comme ça qu’on raconte, (dans) cette histoire, n’est-ce pas!
> > 有一家人……是这样讲的，这个故事，是吧？
> > ① le ton de «histoire» se déploie sur le démonstratif.
> > ② d’abord noté /‡pi˩ ɲi˧/; en fait: est le début d’un mot phonologique: /pi˧ ɲi˥/. Sens: vérifié: est la copule, dans son emploi grammaticalisé servant à renforcer l'affirmation; ce n'est pas le verbe «vouloir, avoir besoin de».
> > ③ le ton du numéral connaît une modification inattendue dans ce contexte, blablabla

dans cet exemple, on affiche donc qu'il y a les notes 1 et 2 au niveau de la phrase, plus précisément au niveau de la transcription de la phrase. Que faut-il prévoir pour une phrase avec des notes mais sans transcription ?

**Comment by alexis-michaud** [comment]
Tu veux dire un truc comme ceci ? 
```
<S>
    <NOTE ...>
</S>
```
(sans élément `<FORM>`)

Ou la même chose pour un mot ou un morphème : qu'il s'y rattache une note, mais pas de forme. 

Réponse simple : ça ne devrait pas exister :) Une note ne devrait porter que sur un contenu qui s'affiche avec un élément `<FORM>`. S'il y a une note sans forme à laquelle elle se rattache, il n'y a pas lieu de l'afficher. L'appel de note doit se faire à partir d'une forme. 

Autrement dit, pas la peine de s'embêter à afficher une note qui se rattache à un élément qui n'apparaît pas dans le lecteur. 

Commentaire au passage : je pense que tu as atteint ici le sommet de complexité qu'on peut trouver dans le format Pangloss... et dépassé (d'une bonne distance) tout ce qui existe actuellement dans la collection. C'est bon signe, sans doute que tu as achevé le "tour du propriétaire" !

**Comment by alexis-michaud** [comment]
Suivi temps réel : le document REWARD (XML [ici](https://github.com/alexis-michaud/na/blob/master/TEXT/F4/crdo-NRU_F4_REWARD.xml)) est mis à jour dans la version décrite ci-dessus, avec une note au niveau du mot. 

Ses identifiants sont [ici](https://cocoon.huma-num.fr/exist/crdo/meta/cocoon-1d91ab4c-fea9-3fd7-976f-e6753a255d1c).

Il faut maintenant que ça passe le stade de l'archivage par Cocoon. 
On avance !

**Comment by m8nli9ht** [comment]
En attendant de tester la nouvelle version, voilà ce que ça donne pour les notes au niveau de la phrase :
![image](https://user-images.githubusercontent.com/6407776/100247107-43617080-2f3a-11eb-8ed3-506f6fe87dca.png)

**Comment by alexis-michaud** [comment]
C'est en ligne. Phrase 154 :

```
		<W>
			<FORM>ʈʰæ˧mi˧-ɳɯ˩</FORM>
			<NOTE xml:lang="fr" message="ʈʰææ̃˧ / ʈʰæ˧mi˧-ɳɯ˩: initiale réalisée proche de [ʈʂʰ]"></NOTE>
			<TRANSL xml:lang="fr">vraiment</TRANSL>
		</W>
```

**Comment by m8nli9ht** [comment]
Traité, sera visible dans le prochain build
