### ISSUE TITLE
affichage traduction texte entier

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#18]
Pour l'instant, l'option 'Traduction texte entier' n'est pas proposée qd il n'y a pas ce contenu 'tout prêt' dans le XML. L'option est 'inerte' sur l'interface (en bas à droite dans l'image ci-dessous) :
![image](https://user-images.githubusercontent.com/6072524/97970479-e1da3600-1dc1-11eb-8a8b-9a005e9b37b4.png)

A faire : de même que pour la transcription du texte entier (#8 ), quand la traduction texte entier n'existe pas dans le XML, on la crée en concaténant les traductions présentes au niveau des unités `<S>` (avec un espace entre chaque phrase).

**Comment by m8nli9ht** [comment]
Traité. Vérifier si la mise en forme est convenable ou non.
Sera visible dans le prochain build.

**Comment by alexis-michaud** [comment]
Ca marche ! 👍
