### ISSUE TITLE
document qui ne s'affiche pas : un TEXT (doi.org/10.24397/pangloss-0004338)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#19]
Un exemple dont on avait déjà parlé, à mon souvenir

corpus/show?oai_primary=cocoon-702bbb09-377a-3a2e-b687-d68b22eaa564&oai_secondary=cocoon-0b19f353-0929-3cb1-ad83-a150689c9615

Dans l'interface Pangloss v1 : 
https://doi.org/10.24397/pangloss-0004338

Dans l'interface Pangloss v2 : 'page blanche'
![image](https://user-images.githubusercontent.com/6072524/98466258-a5964380-21ce-11eb-9ad0-d0df0e9b458c.png)

@m8nli9ht @EdouardSombie ce serait bien que vous fassiez une liste de documents (une dizaine ?) pour lesquels vérifier, après chaque mise à jour du lecteur, qu'ils s'affichent correctement...?

**Comment by alexis-michaud** [comment]
Pas mieux sur le lecteur Eastling 'hors site', semble-t-il ?

https://eastling.huma-num.fr/player/?oai_primary=cocoon-702bbb09-377a-3a2e-b687-d68b22eaa564&oai_secondary=cocoon-0b19f353-0929-3cb1-ad83-a150689c9615

Le son est bien chargé, mais les 'cartes' sont vides.

![image](https://user-images.githubusercontent.com/6072524/98483349-d6df3580-2207-11eb-98d9-550c6571c02e.png)

**Comment by m8nli9ht** [comment]
Document en erreur

https://eastling.huma-num.fr/player/?oai_primary=cocoon-fdc32ca9-f692-3ddd-8f51-e3466979aebe&oai_secondary=cocoon-805174ec-a45d-3e1a-aa67-dd933d42ed99

**Comment by alexis-michaud** [comment]
C'est bon ça marche ! 👍
