### ISSUE TITLE
Lecteur pour site Pangloss v2 : documents qui ne s'affichent pas

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#2]
Documents qui posent problème actuellement : 

- vidéo : 
show?oai_primary=cocoon-008b098b-cf6d-49b9-a26c-a041e12c0688&oai_secondary=cocoon-b5444451-9e1a-4436-9c85-d6c9a0ca3db9
(document kakabé)
l'annotation ne s'affiche pas

[je ne mets que la fin de l'URL pour que les robots du monde entier ne rentrent pas sur le nouveau site avant l'heure ^^ Avec cette URL tronquée on a déjà les identifiants, bien "environnés".]

- manuscrits : 
show?oai_primary=cocoon-0d9175f1-3110-3b86-88ee-abc1ca33b096&oai_secondary=cocoon-ea167a26-448c-3ac3-8a66-c4faf8c18b71
La boîte qui met en valeur la partie du texte qu'on entend entre dans une zone "blanche" : souci d'alignement entre la boîte et le texte

- audio : 
(liste à continuer @sguillaume @doudou-git )

**Comment by m8nli9ht** [comment]
Pour le document vidéo, les annotations ne s'affichent pas car la version actuelle ne gère pas les morphèmes. Je règle ce problème dans le prochain sprint.

**Comment by m8nli9ht** [comment]
Concernant le manuscrit Lai Pao, le problème ne se présente pas chez moi, peut-être me préciser sur quel device et avec quelle résolution le bug est apparu.
![image](https://user-images.githubusercontent.com/6407776/96362575-a0455c00-112e-11eb-8652-f2ff483d7efd.png)

**Comment by alexis-michaud** [comment]
alors je suis en : 1920 x 1200 pixels
diagonale d'affichage : 23.6"
dimensions (largeur x hauteur) : 20 x 12.5

Chrome 86.0.4240.75 (64-bit)

Windows 10

**Comment by alexis-michaud** [comment]
Pour indiquer où on "quitte la route" : c'est sur le mot baːw⁴
![image](https://user-images.githubusercontent.com/6072524/96369287-49a14780-1159-11eb-902b-6b877e168483.png)
On est sur la 1e phrase.

**Comment by alexis-michaud** [comment]
C'est sans doute un problème de défilement horizontal ? Il semble que la taille dévolue à l'image soit exactement *double* de sa taille réelle.
![image](https://user-images.githubusercontent.com/6072524/96409093-07bde300-11e5-11eb-967e-d142268becf5.png)

D'ailleurs, est-il indispensable d'avoir un ... je ne sais pas comment ça s'appelle : une barre de défilement sous l'image, pour se déplacer de gauche à droite ? pareil pour le mouvement vertical ? Les bandes de manuscrits étant "prédécoupées" pour affichage, c'est dommage de devoir se déplacer. Ce serait super si on pouvait voir les "bandes" de manuscrit en entier sans se déplacer verticalement ni horizontalement.

**Comment by m8nli9ht** [comment]
Traité : morphèmes (fichier vidéo OK)

**Comment by m8nli9ht** [comment]
Pour moi le bug du carré blanc devrait faire l'object d'un ticket à part car cela concerne autre chose que ce qui est décrit dans ce ticket "documents qui ne s'affichent pas". Après tests sur la version que je viens d'envoyer à Edouard, on pourra clôturer ce ticket et tu pourras en créer un autre à propos du carré blanc.
