### ISSUE TITLE
Le player ne gère pas les WORDLIST

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#20]
pour exemple :
http://localhost:3000/player?oai_primary=cocoon-f2ccf71a-1f4b-3499-b644-e025720d242c&oai_secondary=cocoon-41d307b9-d0e9-34b9-bfde-4af3af054a68

**Comment by m8nli9ht** [comment]
Traité. A noter cependant 2 choses :

1. La liste des langues de traductions disponibles apparaissent dans l'option "Glosses" et non plus "Translations" comme pour la v1 (pour être en accord avec le fonctionnement pour les docs de type "TEXT")

2. Les traductions sont regroupées dans la même colonne

Sera visible dans le prochain build

**Comment by alexis-michaud** [comment]
"les traductions sont regroupées dans la même colonne" : pas sûr de ce que cela veut dire. Dans la même colonne d'affichage ?

Par exemple pour ce document
https://doi.org/10.24397/pangloss-0001642
(et pour tous les autres documents qui utilisent la liste de vocabulaire EFEO-SOAS-CNRS)
il y a plein de colonnes pour bien distinguer les traductions en diverses langues : autant que de langues. 

![image](https://user-images.githubusercontent.com/6072524/99847701-c7051100-2b78-11eb-9db7-a571923ffa0e.png)

Plutôt que d'avoir "Autres" comme unique boîte à cocher pour les autres langues, ce serait super de pouvoir les afficher (code à 2 lettres, celui qui se trouve dans le XML). Ici : du khmer, dans les 3 colonnes de droite.

**Comment by m8nli9ht** [comment]
> 
> 
> "les traductions sont regroupées dans la même colonne" : pas sûr de ce que cela veut dire. Dans la même colonne d'affichage ?
> 
> Par exemple pour ce document
> https://doi.org/10.24397/pangloss-0001642
> (et pour tous les autres documents qui utilisent la liste de vocabulaire EFEO-SOAS-CNRS)
> il y a plein de colonnes pour bien distinguer les traductions en diverses langues : autant que de langues.
> 
> ![image](https://user-images.githubusercontent.com/6072524/99847701-c7051100-2b78-11eb-9db7-a571923ffa0e.png)
> 
> Plutôt que d'avoir "Autres" comme unique boîte à cocher pour les autres langues, ce serait super de pouvoir les afficher (code à 2 lettres, celui qui se trouve dans le XML). Ici : du khmer, dans les 3 colonnes de droite.

C'est OK, je laisse la mise en forme des cellules (bordure et couleurs) à Edouard pour intégration. Sera visible dans le prochain build.

**Comment by m8nli9ht** [comment]
régression concernant les notes à traiter suite aux dernières modifications (niveaux de transcriptions et translations)

**Comment by m8nli9ht** [comment]
Ok traité !
Par contre le document Wordlist que j'ai ne contient pas les balises de temps pour les words, donc je n'ai pas pu tester le positionnement sur le bon mot
