### ISSUE TITLE
icône pour affichage des numéros DOI

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#21]
utiliser l'icône "officielle" des DOI

![image](https://user-images.githubusercontent.com/6072524/98922632-f8c00d00-24d2-11eb-8f68-6a610051cde5.png)

et l'afficher à côté du titre du document, ainsi qu'à chaque unité de premier niveau (S pour les textes, W pour les listes de mots)

**Comment by alexis-michaud** [comment]
@EdouardSombie pour intégration au site

**Comment by m8nli9ht** [comment]
à traiter côté intégration par Edouard?

**Comment by m8nli9ht** [comment]
je vais traiter côté lecteur, par contre possible de l'avoir avec fond transparent ?

**Comment by m8nli9ht** [comment]
ok traité, sera visible dans le prochain build

**Comment by alexis-michaud** [comment]
@EdouardSombie propose que ce soit simplement une classe, et que l'icône soit ajoutée localement.

Désolé pour les hésitations sur concernant le traitement _au niveau lecteur ou au niveau site web_
Se hace el camino al andar :musical_note:

**Comment by alexis-michaud** [comment]
@m8nli9ht tu as vu avec Edouard ? sa suggestion que ce soit simplement une classe, et que l'icône soit ajoutée localement, a-t-elle été suivie ? 
A ajouter le cas échéant dans les notes pour la documentation ? 
et ensuite tu peux bien sûr fermer le ticket
Merci bcp !

**Comment by m8nli9ht** [comment]
@alexis-michaud Edouard m'a dit (par email) de supprimer l'attribut "src" de l'image DOI ce que j'ai fait et c'est en production. Il a donc sûrement son idée pour traiter en intégration j'imagine.
