### ISSUE TITLE
Gérer les traductions de libellés pour les options d'affichage et autres (no annotation, ...)

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#24]
Uniquement en anglais et français

**Comment by m8nli9ht** [comment]
A-t-on liste des libellés avec leur traduction en anglais ?

**Comment by EdouardSombie** [comment]
Non, on ne les a pas.
A mon avis, le mieux c'est que tu les gères dans react.

**Comment by alexis-michaud** [comment]
Dans la v1 il y a des éléments qui devraient pouvoir être repris. 
Peut-être préciser, pour les Gloses (anglais : Glosses) : cocher "Mots" et "Morphèmes", selon ce qui est disponible dans le XML. Cf CNRS-LACITO/Pangloss_website#252 : 
- quand on a <FORM> et <TRANSL> au niveau du mot et du morphème, il faut proposer les 2 options : "Mots" ("Words") et/ou "Morphèmes" ("Morphemes") ; 
- quand il n'y a qu'un des 2 niveaux (W ou M) qui soit renseigné (qui contient <FORM> et <TRANSL>), dans ce cas on ne met qu'un bouton "Gloses" ("Glosses"), sans sous-options

**Comment by alexis-michaud** [comment]
@m8nli9ht ce ticket peut-il maintenant être fermé ?

**Comment by m8nli9ht** [comment]
Oui!

Le mar. 29 déc. 2020 à 17:42, Alexis Michaud <notifications@github.com> a
écrit :
