### ISSUE TITLE
stabiliser la boîte avec les options à cocher ("Display options")

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#25]
Organisation bien lisible et structurée de la boîte avec les options à cocher ("Display options"), d'une façon qui soit stable d'un document à l'autre dans la mesure du possible. 

L'essentiel : que les cases à cocher soient bien associées visuellement au niveau auquel elles correspondent. Par exemple "Gloses" en fin de ligne et cases à cocher en début de ligne suivante est pas optimal. 

Aussi : ne pas afficher en grisé les options "Transcription", "Whole text translation", "Glosses"... sinon on a l'impression que c'est **désactivé**.

![image](https://user-images.githubusercontent.com/6072524/99522384-dc6e1580-2995-11eb-8b10-06f3c59516ea.png)

**Comment by m8nli9ht** [comment]
Visio du 20/11/2020 : regrouper les balises legend et options dans la même div !

**Comment by m8nli9ht** [comment]
> 
> 
> Organisation bien lisible et structurée de la boîte avec les options à cocher ("Display options"), d'une façon qui soit stable d'un document à l'autre dans la mesure du possible.
> 
> L'essentiel : que les cases à cocher soient bien associées visuellement au niveau auquel elles correspondent. Par exemple "Gloses" en fin de ligne et cases à cocher en début de ligne suivante est pas optimal.
> 
> Aussi : ne pas afficher en grisé les options "Transcription", "Whole text translation", "Glosses"... sinon on a l'impression que c'est **désactivé**.
> 
> ![image](https://user-images.githubusercontent.com/6072524/99522384-dc6e1580-2995-11eb-8b10-06f3c59516ea.png)

Les libellés sont "grisés" par défaut dans la feuille de style. Il suffit de changer ça côté intégration et appliquer le style correspondant aux libellés dans la charte graphique de Pangloss

**Comment by m8nli9ht** [comment]
- Enlever les libellés de l'affichage si pas d'option dispo

- Whole text transcription / Words au dessus ou à gauche

- Encapsuler dans une même div "S1 play/pause" pour qu'Edouard puisse les faire flotter

**Comment by alexis-michaud** [comment]
Peut-être à voir en lien avec le ticket #38 ? et fermer les 2 tickets une fois que les développements qui y sont mentionnés auront été réalisés & la nouvelle version mise en production ?
