### ISSUE TITLE
utilisation de couleurs pour mise en valeur des diverses dimensions du texte ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#26]
Les documents Pangloss sont du texte structuré logiquement. Ca permet de jouer sur les couleurs, les tailles de police... pour bien mettre en page les textes qui sont déjà bien enrichis (et ça encourage les déposants à parvenir à ce stade).

Eviter les italiques (déconseillé pour les caractères phonétiques ; limiter aux mots d'emprunts ?) et ne pas trop trop abuser du gras (certains esthètes de la typographie désapprouveraient !) mais utiliser des codes couleur (avec modération) pour bien structurer visuellement les pages d'affichage. 

@EdouardSombie des idées ? (c'est fortement lié à l'intégration sur le site)

**Comment by alexis-michaud** [comment]
Parmi les points de référence possible : l'interface des corpus du labo LLACAN

Un exemple ici : 
https://corporan.huma-num.fr/Archives/afficheTout_N2.php?ref=0%20:%20HAU_BC_CONV_03.EAF%20:%200
![image](https://user-images.githubusercontent.com/6072524/99533766-b7ce6980-29a6-11eb-907d-1105b5a5f1d0.png)

**Comment by alexis-michaud** [comment]
Pour ma part j'aime bien la façon dont le grisé en fond sépare les mots. 
(C'est évidemment pas tout à fait identique aux documents de Pangloss. En plus des niveaux de Pangloss, il y a 2 niveaux mot/morphème, et une 4e ligne pour les classes morphosyntaxiques : "parties du discours" : nom, verbe, conjonction, etc., noté dans les règles de l'art : N pour nom, etc.)

**Comment by m8nli9ht** [comment]
Visio du 20/11/2020 : ajouter des classes CSS à chaque niveau (Text, Sentence, Word, Morph, Note, ....) 
Communiquer le nom des classes à Edouard

**Comment by m8nli9ht** [comment]
J'ai créé les classes CSS : TEXT, SENTENCE, WORD, MORPHEME (visible dans le prochain build)
Pour NOTE cela attendra le traitement du ticket #17

**Comment by alexis-michaud** [comment]
Ca roule :smiley:
