### ISSUE TITLE
Infos cochées par défaut pour le lecteur, mode "pro" et "normal"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#27]
Je crée ici un doublon d'[un ticket plus détaillé qui figure dans le dépôt Pangloss](https://github.com/CNRS/Pangloss/issues/111), pour attirer l'attention sur cette modif', qui serait à faire **dès que possible**, si possible dès le _build_ du jour.

Pour l'instant les boîtes sont vides et il faut tout cocher case par case. Principe général : par défaut, afficher les gloses interlinéaires complètes (information tout à fait cruciale : niveau des mots et des morphèmes), ainsi que les différentes transcriptions et traductions. L'utilisation décoche ce qui ne l'intéresse pas.

(Voir détails sur le ticket [dans le dépôt Pangloss](https://github.com/CNRS/Pangloss/issues/111))

**Comment by m8nli9ht** [comment]
Comment faire alors la différence entre le cas où cette option n'a pas été cochée du fait d'une première consultation, du cas où l'utilisateur a volontairement décoché cette option ?

**Comment by alexis-michaud** [comment]
Voici un exemple. Quand l'URL contient une syntaxe de consultation 'nue', sans options : 

.../corpus/show?oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee

les infos sont affichées. 

Ensuite, à mesure que l'utilisateur décoche des trucs, l'URL est mise à jour. 
Ca pourrait marcher ?

**Comment by alexis-michaud** [comment]
Autrement dit, l'affichage par défaut serait l'équivalent de celui-ci : 
.../corpus/show?oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&optionWords=true&optionTranscriptions=%2Bphono%2Bortho%2Bphonetic&optionTranslations=%2Bfr%2Ben%2Bzh&optionGlosses=%2Bfr%2Ben&optionNotes=&optionWholeTranscriptions=false&optionWholeTranslations=

**Comment by m8nli9ht** [comment]
L'URL est mise à disposition dans le site Pangloss donc à faire côté intégration peut-être ?

**Comment by EdouardSombie** [comment]
Ok pour passer des paramètres par défaut au player.
Mais certains paramètres risquent de ne pas toujours être disponibles (fonction des annotations), non ?

**Comment by alexis-michaud** [comment]
Bien vu ! Tout à fait. A vue de nez, mieux vaudrait "déballer" **ce qui est disponible dans le document**, selon les indications fournies dans le ticket référencé en haut de page, et que l'URL s'ajuste **ensuite** pour refléter les choix faits par l'utilisateur. 
Du coup je vous conseillerais de voir ensemble en direct @EdouardSombie @m8nli9ht

**Comment by m8nli9ht** [comment]
Traité. Si aucune valeur n'est définie au départ, le lecteur "coche" par défaut :

- la première option disponible de type de transcription

- la première option disponible de langue de traduction

- mot à mot

- la première option disponible de langue de gloses

- la première option disponible de langue de note

**Comment by m8nli9ht** [comment]
... /corpus/show?**lang=fr**&oai_primary=...

Récupérer la langue dans le paramètre de l'URL, si rien => "fr"

**Comment by alexis-michaud** [comment]
Ticket fermé pour l'instant, la suite dans [le ticket 111 du dépôt Pangloss](https://github.com/CNRS/Pangloss/issues/111) ? (mais n'hésitez pas à rouvrir si c'est utile @m8nli9ht @EdouardSombie )

**Comment by alexis-michaud** [comment]
Bon, je rouvre, le temps de refaire un bilan de ce qui doit être coché / décoché :

- les notes ne doivent pas être cochées par défaut, ni en mode pro ni en mode grand public. (Pour l'instant, 30 décembre, elles sont cochées par défaut)
- le mot à mot n'est pas coché par défaut (niveaux mot et morphème)

**Comment by sguillaume** [comment]
Tout à fait d'accord sur les choix ! 
👍

**Comment by m8nli9ht** [comment]
Traité (au final, il ne reste que les transcriptions et traductions de phrase par défaut).

**Comment by m8nli9ht** [comment]
Livré. A contrôler et clôturer

**Comment by alexis-michaud** [comment]
Pour le mode grand public : c'est bon

Pour le mode pro : afficher par défaut 

- toutes les transcriptions au niveau S
- le niveau W et/ou M selon ce qui est présent dans le XML. (Si les 2 existent : cocher W et M.) Afficher toutes les transcriptions (par ex.: phono et orthographe) et toutes les traductions. 
Le reste demeure non coché (notes...)

**Comment by m8nli9ht** [comment]
Gérer un nouveau paramètre "mode" dans l'URL qui peut prendre en valeur "pro" ou "normal"

**Comment by m8nli9ht** [comment]
traité, livré, à contrôler
