### ISSUE TITLE
Whole text transcription

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#28]
toutes les options dispo doivent avoir soit la transcription complète (dans la balise TEXT) ou la concaténation des transcriptions.

**Comment by m8nli9ht** [comment]
C'est déjà traité en réalité je n'ai rien touché. Je me demande pourquoi on a saisi ce ticket => des cas où ça ne marche pas ?

**Comment by alexis-michaud** [comment]
Oui, tu te souviens, quand on avait regardé ensemble, on avait constaté que la concaténation ne fonctionnait pas. C'est toujours le cas. 

Un exemple : ... corpus/show?oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&optionWords=true&optionTranscriptions=phono&optionTranslations=fr&optionGlosses=fr&optionNotes=&optionWholeTranscriptions=true&optionWholeTranslations=

![image](https://user-images.githubusercontent.com/6072524/101135919-cfdff300-360c-11eb-8779-49372a8aa619.png)

Le bouton "Whole text transcription" est poussé, et la cache "phono" est cochée, de sorte qu'une transcription du texte entier devrait être affichée.

Celle-ci n'étant pas disponible "toute faite" (une `<FORM kindOf="phono">` au niveau du texte entier), il faut la produire par concaténation. 

Est-ce plus clair comme ça ... ?

**Comment by m8nli9ht** [comment]
Merci! Maintenant je me souviens de la cause du problème !

**Comment by m8nli9ht** [comment]
Ok traité, à tester à la prochaine livraison du build

**Comment by alexis-michaud** [comment]
Ca marche ! 👍 :smiley:
