### ISSUE TITLE
Phrase courante : classe CSS + event JS

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#29]

**Comment by m8nli9ht** [comment]
Ok traité, pas exactement comme prévu mais on verra si ça convient à Edouard :
Je lance un event "Sentence changed" au niveau du document, et je met à jour une variable "currentSentence" avec l'ID de la phrase.
Visible au prochain build

**Comment by EdouardSombie** [comment]
Salut,
Ca me convient comme mécanisme :)
@Matthew: tu penses compiler le nouveau build quand ça ?

**Comment by m8nli9ht** [comment]
@EdouardSombie parfait ! Je finis d'avancer sur le ticket 22 et je builde !

**Comment by m8nli9ht** [comment]
@alexis-michaud : Pour ce ticket, c'est @EdouardSombie qui pourra dire si c'est OK (je l'ai mis en production déjà)

**Comment by EdouardSombie** [comment]
C'est ok :)
