### ISSUE TITLE
affichage des identifiants : DOI

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#3]
Pour l'instant, les DOI ne sont pas récupérés. Quand on clique sur le bouton, les adresses données ne comportent que le préfixe et le numéro de phrase, le DOI proprement dit manque. 
Ex.: 
https://doi.org/#S1

![image](https://user-images.githubusercontent.com/6072524/96369402-eb289900-1159-11eb-9efa-389640b78169.png)

**Comment by m8nli9ht** [comment]
Je construis simplement une URL composée d'un script (citation_doi.php) qui prend les paramètres doi et sentence, selon ce qui existe sur le pangloss actuel.
Par contre, je ne sais pas ce que fait le script citation_doi.php, et donc je ne peux pas dire si le résultat présenté est juste ou faux !
