### ISSUE TITLE
Créer une carte au niveau du mot et imbriquer les morphèmes

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#30]
https://pangloss.cnrs.fr/ ... /corpus/show?lang=fr&mode=pro&oai_primary=cocoon-7d6235a0-7b5a-416d-8077-01eae61efd28&oai_secondary=cocoon-b1d1b067-16fd-47db-b3c5-60ed2dd45045&optionGlosses=&optionNotes=&optionTranscriptions=%2Bother&optionTranslations=%2Bbo%2Bfr%2Ben&optionWholeTranscriptions=false&optionWholeTranslations=&optionWords=true

**Comment by m8nli9ht** [comment]
possible d'avoir un exemple de document avec Mot (+ transcription + translation au niveau du mot) contenant des Morphèmes (eux-mêmes avec transcriptions et translations)?

**Comment by m8nli9ht** [comment]
J'ai trouvé ce texte : 
oai_primary=cocoon-9245e7d0-3e19-3eac-8f3e-2dc3a04bbf43
oai_secondary=cocoon-b5285065-cb88-3de1-b3d6-9cab013681f7 

Du coup j'ai un cas à la phrase 122 :
![image](https://user-images.githubusercontent.com/6407776/101059886-0ecf6380-358f-11eb-81d7-697279fd3ba2.png)

**Comment by m8nli9ht** [comment]
Traité. La difficulté à présent est de présenter les choses "proprement" dans l'intégration

**Comment by m8nli9ht** [comment]
Petit oubli : dans le cas où le mot a des morphèmes : 

- si une transcription existe au niveau du ot on l'affiche
- sinon : doit-on concaténer la forme des morphèmes ou laisse-t-on vide ?

**Comment by alexis-michaud** [comment]
Oui, il faut concaténer la forme des morphèmes. Ainsi l'utilisateur voit les mots et les morphèmes. Ne pas laisser vide la `<FORM>`, à aucun niveau. Si les cases Mot, Morphème, Phrase, Texte... sont cochées, on affiche une forme, soit en prenant celle fournie dans le XML s'il y en a, soit en concaténant ce qui est présent au niveau du dessous.

Autrement dit : 
- on crée la forme du mot en concaténant les morphèmes, avec comme séparateur un tiret --sauf s'il y a déjà un tiret ou signe égal
- on crée la forme du texte en concaténant les phrases, avec comme séparateur un espace
- en principe on pourrait même créer la forme de la phrase en concaténant les mots, et en mettant un espace entre chacun des mots ; je ne crois pas que la question se pose et on n'est pas obligé de prévoir ça, mais c'est pour expliquer la logique, qui s'applique pareillement à chacun des niveaux.

**Comment by alexis-michaud** [comment]
Si ça fait trop d'info, des choses redondantes... l'utilisatrice peut dé-cocher à sa guise. Mais c'est important que le lecteur offre tous les niveaux, et un choix très fin dans ce qu'on souhaite afficher.

**Comment by m8nli9ht** [comment]
ok traité, à tester après la mise à niveau du build

**Comment by m8nli9ht** [comment]
Je pense que ce ticket n'est pas clôturé car une discussion reste en cours entre @sguillaume  et @alexis-michaud pour savoir si on concatène les formes de Morphèmes au niveau du Word si le Word a lui-même déjà une forme définie.

**Comment by alexis-michaud** [comment]
Non non, pour ça on a la réponse. **Si le W (Word) a déjà une forme définie, on ne concatène pas les formes de Morphèmes**. C'est uniquement dans le cas de figure où il y a des FORM au niveau M **et non au niveau W** qu'on propose cette concaténation.

**Comment by alexis-michaud** [comment]
@m8nli9ht si l'info contenu dans le dernier commentaire ci-dessus te convient, ce ticket peut être clôturé
