### ISSUE TITLE
afficher le DOI dans une pop-up

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#31]
span au même niveau que l'image qui contienne l'URL

**Comment by m8nli9ht** [comment]
Traité. Par contre je ne l'ai pas mis au même niveau que l'image, j'ai utilisé les paramètres par défaut du composant natif du framework afin que l'utilisateur puisse facilement copier l'URL. A voir si on ajuste au moment de l'intégration.

**Comment by m8nli9ht** [comment]
A clôturer ?

**Comment by alexis-michaud** [comment]
Tout à fait ! (N'hésite pas à clôturer toi-même)
