### ISSUE TITLE
Changer le parser pour avoir les langues et formes dispos par niveau (texte, phrase, mot, morphème)

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#32]

**Comment by m8nli9ht** [comment]
impact sur parserMySQL et composants (Display Options notamment)

**Comment by m8nli9ht** [comment]
J'ai commencé par modifier le parser de XML et c'était assez rapide. 
Par contre, le reste va prendre plus de temps car je dois repasser dans chaque composant du lecteur (Options, Sentence, Word, Note, ..et Morpheme que je vais créer vu qu'au final il se comporte différemment de Word et nécessite un code à part). 

Je priorise ce ticket car c'est le plus "touchy"

**Comment by alexis-michaud** [comment]
Super. Merci de prendre à bras le corps le gros boulot qui consiste à proposer un affichage d'une finesse de dentelle, qui tire le meilleur parti de tous les aspects du format XML des documents. C'est le cœur du lecteur, et du site !

**Comment by m8nli9ht** [comment]
Une chose à laquelle on a pas pensé : cela implique également de reconstruire l'URL avec tous ces nouveaux paramètres (text transcription, text translation, sentence transcription, sentence translation, word...etc)

**Comment by alexis-michaud** [comment]
Tout à fait.
Le grand nombre de paramètres encouragerait à chercher une forme abrégée, aussi courte que possible,
même si cela rend les paramètres moins évidents à interpréter à l’œil.

**Comment by m8nli9ht** [comment]
ok traité, à tester lors de la livraison du prochain build
