### ISSUE TITLE
Problème d'affichage des annotations au niveau W

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#35]
Les annotations de cette ressource ne s'affichent pas pour moi : 

https://pangloss.cnrs.fr/v2/corpus/show?lang=fr&oai_primary=cocoon-58ce5a06-b349-358a-b56d-5f77130ed999&oai_secondary=cocoon-480e5ff5-5441-3b4d-bd38-750df87ee98b

C'est une ressource qui possède uniquement un niveau S/W directement.
(Aucune transcription ou traduction au niveau de S ni au niveau de M)

**Comment by alexis-michaud** [comment]
Bien vu ! 
Pareil par chez moi, même en rechargeant la page.
![image](https://user-images.githubusercontent.com/6072524/102211842-82993680-3ed4-11eb-9a7d-7dc1a7ff495c.png)

**Comment by m8nli9ht** [comment]
Je suis dessus

Le mar. 15 déc. 2020 à 12:53, Alexis Michaud <notifications@github.com> a
écrit :

**Comment by alexis-michaud** [comment]
Ca marche ! :smiley: 👍
