### ISSUE TITLE
affichage DOI pour WORDLIST

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#36]
Attention, pour l'instant les documents de type WORDLIST n'ont pas l'affichage des DOI

Exemple : https://pangloss.cnrs.fr/ ... /corpus/show?lang=fr&mode=pro&oai_primary=cocoon-bb37b586-9997-3081-9a2f-d06f0c2a3c71&oai_secondary=cocoon-75257e89-abfe-3a85-bee8-c393c13496e0

![image](https://user-images.githubusercontent.com/6072524/102872014-7286d700-443f-11eb-9e48-9f0a7ee0d452.png)

Toutes les unités de 1er niveau ont un 'bouton' DOI. Pour un document de type TEXT c'est l'unité S, pour les WORDLIST c'est l'unité W.

Question du lecteur ou d'intégration ? @m8nli9ht

**Comment by EdouardSombie** [comment]
Salut,
Le player ne semble pas afficher le lien.
C'est une mission pour MoonLight :)

**Comment by m8nli9ht** [comment]
ok traité

**Comment by alexis-michaud** [comment]
On embraye sur un autre ticket :) le #40 
(pour aligner le traitement des DOI des WORDLIST sur celui des TEXT, pour lesquels ça fonctionne déjà très bien)
