### ISSUE TITLE
interaction entre boutons DOI et ... numérotation des notes

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#39]
Un truc d'assez haute voltige informatique, candidat _in extremis_ au concours du bogue Pangloss le plus craquant de l'année 2002 :grin: **Cliquer sur le bouton d'un DOI modifie... la numérotation des notes de l'unité S concernée.**

Ca se passe [ici](https://pangloss.cnrs.fr/v2/corpus/show?lang=&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&optionGlosses=fr&optionNotes=%2Bfr&optionTranscriptions=phono&optionTranslations=fr&optionWholeTranscriptions=true&optionWholeTranslations=&optionWords=true&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=phono&optionSentenceTranslations=fr&optionWordTranscriptions=other&optionWordTranslations=fr&optionMorphemeTranscriptions=other&optionMorphemeTranslations=fr).

Au départ (avant de cliquer sur des boutons DOI), la numérotation des notes part de 1 pour chaque phrase. 

![image](https://user-images.githubusercontent.com/6072524/103310931-317f5b80-4a19-11eb-9b2e-12a290adb775.png)

Un clic sur le bouton DOI de la phrase 4 (S4) fait commencer la numérotation... à 2 pour les phrases 2 et 4, **qui ont leur DOI affiché**. La phrase 5 ne bouge pas (numérotation à partir de 1).

![image](https://user-images.githubusercontent.com/6072524/103310997-69869e80-4a19-11eb-976f-bf88488a6282.png)

Et quand on décoche (nouveau clic sur l'icône DOI, qui fait disparaître l'affichage du DOI), la numérotation commence... à trois :smiley: 
![image](https://user-images.githubusercontent.com/6072524/103311096-b4081b00-4a19-11eb-9296-90d088ac6fa0.png)

La phrase 5 ne bouge toujours pas.
Intéressant et cocasse ! 

Pour essayer de trouver la régularité : 
**Soit n le nombre de notes associées à une phrase. Quand on clique sur le bouton d'un DOI, cela incrémente le compteur de notes de la phrase concernée de n.** Au lieu de commencer à 1, le compte des notes commence donc à n + 1. S'il y a 1 note, elle sera notée 1+1 = 2. S'il y a 3 notes, elles seront notées de 4 à 6. S'il y a 4 notes (ex.: phrase 115), elles seront notées de 1+4 à 4+4, donc de 5 à 8. 

Un petit élément de complexité est que les notes rattachées au niveau du `TEXT` entier s'invitent dans le décompte de notes de la **première phrase** (S1), lorsqu'on clique sur le bouton "DOI" de celle-ci.

**Comment by alexis-michaud** [comment]
C'est vraiment amusant à explorer ! C'est incrémental au fil des clics. Si on clique et reclique sur un même DOI, le compteur grandit. C'est ainsi qu'on peut obtenir un appel de note numéro 130 (avec toujours une bonne correspondance entre numéro d'appel de note et numéro de note) en cliquant tout son saoul sur le bouton DOI de la phrase 2

![image](https://user-images.githubusercontent.com/6072524/103311900-d1d67f80-4a1b-11eb-8c4d-38b37f5f3631.png)

Les clics font alternativement apparaître et disparaître le DOI... et le compteur tourne :smiley:

**Comment by alexis-michaud** [comment]
Pour les phrases qui ont plusieurs notes, le compteur augmente de n à chaque clic. Ca permet de vérifier au passage que le système des notes est hyper-robuste au compteur : les 4 chiffres de notes sont atteints sans encombres !!

![image](https://user-images.githubusercontent.com/6072524/103312104-57f2c600-4a1c-11eb-89c7-c43ccd88021e.png)

Je m'en tiens là pour ce rapport d'erreur et passe la main au pro :) @m8nli9ht

**Comment by m8nli9ht** [comment]
OK je viens de trouver l'erreur (note technique : le changement d'état du composant entraîne un re-render qui recalcule les index de note => solution : déplacement de l'instruction de remise à zéro dans le render et non pas dans le constructeur)
