### ISSUE TITLE
affichage des textes sans manuscrit : ajustements à réaliser

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#4]
[ticket fermé dans le dépôt "Eastling éditeur" et déplacé ici le 18 octobre 2020]

Ajustements à réaliser pour l'emploi d'Eastling comme lecteur pour tous les documents, dans le cadre de la refonte en cours du site Pangloss :

Pour l'affichage de textes sans manuscrit, par exemple ici : 
.../corpus/Na/cocoon-1fee21d5-125f-313d-aab7-121aa9c2cac5/cocoon-2c55a91e-c666-3033-8d07-09da47d9f2ba

il reste des ajustements à faire et des fonctionnalités à ajouter, de façon à offrir les mêmes possibilités (et plus) que l'interface ancienne (version 1 = "v1"). 

Une comparaison avec la [version 1](https://pangloss.cnrs.fr/corpus/show_text.php?id=cocoon-1fee21d5-125f-313d-aab7-121aa9c2cac5&idref=cocoon-2c55a91e-c666-3033-8d07-09da47d9f2ba) fait ressortir quelques besoins pour la v2 : 

- affichage du DOI du texte entier, ainsi que de chaque phrase (cf #3 )
- choix de la langue pour l'affichage des notes (de même que pour les autres types d'infos).  Par exemple, si quelqu'un ne parle pas français et ne souhaite pas afficher les notes en français. 
- *par défaut*, afficher toutes les infos y compris les gloses interlinéaires (information tout à fait cruciale). L'utilisation décoche ce qui ne l'intéresse pas

**Comment by m8nli9ht** [comment]
en partie réalisé, manque peut-être le 3° point sur lequel un exemple de document serait bienvenu.

**Comment by alexis-michaud** [comment]
Le lun. 19 oct. 2020 à 19:50, m8nli9ht <notifications@github.com> a écrit :

> en partie réalisé, manque peut-être le 3° point sur lequel un exemple de
> document serait bienvenu.

Très bizarre, je ne vois plus ce commentaire sur l'interface GitHub !
Comme exemple : ce texte, par exemple
https://doi.org/10.24397/pangloss-0004352
Sur l'interface v1, le texte et ses gloses interlinéaires sont déployés (affichés) par défaut, et on peut ensuite dé-cocher.

![image](https://user-images.githubusercontent.com/6072524/96497094-6f5a4980-124a-11eb-98e8-d6db8576902f.png)

**Comment by alexis-michaud** [comment]
Comme exemple : ce texte, par exemple
https://doi.org/10.24397/pangloss-0004352
Sur l'interface v1, le texte et ses gloses interlinéaires sont déployés (affichés) par défaut, et on peut ensuite dé-cocher. 

![image](https://user-images.githubusercontent.com/6072524/96497179-90bb3580-124a-11eb-8405-03eddbfcc81b.png)

Pour essayer de récapituler : tout serait coché par défaut, sauf les niveaux "Texte entier" (transcription et traduction)... 
et sauf les Notes en mode "non-pro" ? (les utilisateurs peuvent cocher s'ils veulent, mais c'est décoché par défaut, tandis qu'en mode pro, ça serait coché par défaut ?)
@sguillaume @Doudou-git commentaires bienvenus

**Comment by alexis-michaud** [comment]
Juste pour rappel : cette demande reste à l'ordre du jour : "par défaut, afficher toutes les infos y compris les gloses interlinéaires (information tout à fait cruciale). L'utilisation décoche ce qui ne l'intéresse pas"

Au 27 octobre, seules les notes s'affichent "par défaut", en ouvrant un document.
![image](https://user-images.githubusercontent.com/6072524/97357286-ce970a00-1899-11eb-96e5-988e4504550b.png)

**Comment by alexis-michaud** [comment]
@m8nli9ht : ticket qui renferme plusieurs demande. Je le ferme, et les points qui restent à l'ordre du jour sont déplacés vers Pangloss. 

https://github.com/CNRS/Pangloss/issues/111
