### ISSUE TITLE
DOI : numéroter les unités de 1er niveau (S ou W), ne pas utiliser d'identifiants longs

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#40]
A l'heure actuelle, les DOI des listes de mots (WORDLIST) sont formés en utilisant l'identifiant complet de l'unité de premier niveau : donc le W. 

Ca donne des identifiants DOI comme : `https://doi.org/10.24397/pangloss-0004368#WNumPlusCL_H2_Day_30to100_F4_24Sept2011_AUDIOPLUSEGG_001`

![image](https://user-images.githubusercontent.com/6072524/103352940-d9dc0100-4aa7-11eb-914f-e9ad312caa7a.png)

**Il ne faut pas utiliser les identifiants contenus dans le fichier XML, mais re-numéroter de 1 à n à partir du premier.**

Ainsi, dans [cet exemple](https://pangloss.cnrs.fr/v2/corpus/show?lang=&oai_primary=cocoon-0495876e-1d9e-318a-9f98-982480515c1a&oai_secondary=cocoon-690069fd-5d92-392c-9ba0-78980bac6623), l'identifiant est simplement le DOI du document auquel on ajoute `#W1` :

`https://doi.org/10.24397/pangloss-0004368#W1`

**Comment by alexis-michaud** [comment]
Au fond, il s'agit simplement de traiter les DOI des WORDLIST de façon similaire à ceux des TEXT : au lieu de `#S` suivi du numéro de phrase, on ajoute `#W` suivi du numéro de mot.
C'est déjà fait à la perfection pour les TEXT : par exemple pour [celui-ci](https://pangloss.cnrs.fr/v2/corpus/show?lang=&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee), dans le XML il y a des identifiants 'maison' pour chaque élément S : `<S id="Sister_S001">` et ainsi de suite. Les DOI affichés ne tiennent pas compte de cet `id`, et tout est pour le mieux.
Ainsi, le DOI de la 1e unité S est bien affiché tel qu'on le souhaite : 
https://doi.org/10.24397/pangloss-0004342#S1

Autrement dit, on refait un décompte des unités de 1er niveau sans se préoccuper du contenu des balises S (ou W pour les listes de mots).

**Comment by m8nli9ht** [comment]
Vu. Je traite ce ticket demain ou mercredi.

**Comment by m8nli9ht** [comment]
ok, traité et livré. A tester
