### ISSUE TITLE
Organisation bouton et options pour le mot à mot

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#41]
Pour le mot à mot : le bouton à cocher "Mot à mot" devrait 'chapeauter' quatre niveaux : 
-- Transcription des mots
-- Traduction des mots
-- Transcription des morphèmes
-- Traduction des morphèmes
Pour l'instant c'est séparé, et le bouton vient après tout le reste.

![image](https://user-images.githubusercontent.com/6072524/103356117-55da4700-4ab0-11eb-92b5-c5eb085534b0.png)

Cela pourrait être réorganisé comme ci-dessous ?

![image](https://user-images.githubusercontent.com/6072524/103356196-8fab4d80-4ab0-11eb-80c0-82d77cfd253a.png)

Que se passe-t-il quand le mot à mot (décoché par défaut) est coché ? Une utilité possible serait de cocher, d'un coup d'un seul, **toutes** les options concernant les niveaux W et M (toutes les langues de traduction, notamment). Un souci dans la configuration souhaitée (niveaux W et M décochés par défaut, cf. #27 ), c'est qu'il faudra deux actions pour afficher les niveaux W et M : pousser le bouton "Mot à mot", _et_ cocher les cases souhaitées. **Les cases à cocher sont inertes si le bouton n'est pas poussé.** Ca paraît un peu contre-intuitif. 

Peut-être supprimer carrément le bouton "Mot à mot" (qui d'ailleurs est aussi un "morphème à morphème") et afficher tout "à la carte", selon les cases cochées ?

**Comment by sguillaume** [comment]
Tout à fait d'accord pour supprimer le bouton "Mot à Mot" !
Et juste laisser les cases à cocher pour gérer l'affichage.

**Comment by m8nli9ht** [comment]
ok, traité, je livre dans la foulée

**Comment by m8nli9ht** [comment]
Livré. A contrôler et clôturer
