### ISSUE TITLE
affichage de W concaténés à partir de M : utiliser un séparateur, le tiret

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#42]
Pour l'affichage de mots (W) concaténés à partir de morphèmes (M) : utiliser un séparateur, le tiret, comme convenu.

A l'heure actuelle (30 décembre), les tirets ne s'affichent pas

![image](https://user-images.githubusercontent.com/6072524/103357049-87eca880-4ab2-11eb-98d9-81a7106d68ed.png)

**Comment by m8nli9ht** [comment]
ok vu, je traite dans la journée

**Comment by m8nli9ht** [comment]
ok traité dans le parser, déjà visible, merci de vérifier

**Comment by m8nli9ht** [comment]
Livré. A contrôler et clôturer
