### ISSUE TITLE
Problème transcription 1ère phrase

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#45]
Retour utilisateur : 
"Dans les documents : Quand on lit l'audio en même temps que le
texte, la première ligne (transcription de la phrase, en caractères
gras) ne fait pas partie de la section de l'écran affichée au moment
où on entend l'audio correspondant, c'est dommage"

**Comment by alexis-michaud** [comment]
En effet, c'était un souci d'affichage bien identifié ( [ici](https://github.com/CNRS/Pangloss/issues/125) ), et ça a été corrigé tout récemment (ticket clôturé aujourd'hui même). 
Si tu pouvais transmettre à l'utilisatrice / utilisateur concerné(e), qu'elle ou il re-teste (ou soit au moins informé que le nécessaire a été fait)...?

Tu peux clôturer le ticket si le nouvel affichage te paraît convenir, ou exposer ici des recommandations si tu penses que ça devrait être affiché avec un centrage différent sur la page
Merci bcp !
