### ISSUE TITLE
L'affichage de textes sans chronocodes ne se fait pas

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#46]
Il semble que l'affichage de textes sans chronocodes puisse poser problème. Retour de déposant : **certains textes ne se chargent
jamais ni dans Chrome ni dans Edge, même si je
rafraîchis plusieurs fois la page.** Il semble que ce soit le cas pour certaines annotations qui
n'avaient pas de time code ; pourtant il s'affichait bien sur
l'ancienne version: https://doi.org/10.24397/pangloss-0003334"

C'est ici : https://pangloss.cnrs.fr/v2/corpus/show?lang=fr&oai_primary=cocoon-373e44ee-008b-30ea-a624-ecfb6c4ed409&oai_secondary=cocoon-b6627cac-54d5-3349-b085-939e66a04e0e

![image](https://user-images.githubusercontent.com/6072524/103476214-0e0b3680-4db4-11eb-9b6c-274b057086e5.png)

C'est un ticket pour toi @m8nli9ht ? ou ça concerne l'intégration sur le site ?

**Comment by m8nli9ht** [comment]
ok vu, je règle ça dans la journée

**Comment by m8nli9ht** [comment]
traité, je livre le build plus tard dans la journée

**Comment by m8nli9ht** [comment]
Livré. A contrôler et clôturer
