### ISSUE TITLE
listes de mots : cocher par défaut la transcription du mot et sa traduction

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#47]
Réglage tout récent (hier, 4 janvier) : le lecteur décoche tout par défaut, sauf transcription au niveau S et traduction au niveau S. 

C'est ce qui est souhaité pour les textes (TEXT). Mais pour les listes de mots (WORDLIST), ça donne des pages vides.
![image](https://user-images.githubusercontent.com/6072524/103626084-02e31280-4f3c-11eb-96e3-9f17e5c0c738.png)
(exemple : celui-ci : https://doi.org/10.24397/pangloss-0001641 / oai:crdo.vjf.cnrs.fr:cocoon-5776e7dd-126b-33e4-8e15-112edaa4ce25 )
Il faut donc, pour les listes de mots, cocher par défaut : l'affichage de la forme et de la traduction du niveau W (mot). 

(Au fond le 'cahier des charges' est le chose que pour les TEXT : on affiche le 1er niveau de granularité.)

Quelles traductions afficher : toutes ? (ce serait ma recommandation)

**Comment by m8nli9ht** [comment]
OK je traite d'ici jeudi. Mea culpa j'ai fait ça hier entre 2 séances de
travail au bureau !

Le mar. 5 janv. 2021 à 09:57, Alexis Michaud <notifications@github.com> a
écrit :

**Comment by m8nli9ht** [comment]
traité.

**Comment by m8nli9ht** [comment]
livré, à contrôler

**Comment by m8nli9ht** [comment]
bug : disparition des checkbox sur clic lorsque l'on est en mode pro et que c'est la première consultation (aucune option définie dans URL)

**Comment by m8nli9ht** [comment]
traité.

**Comment by m8nli9ht** [comment]
Livré, à tester.
