### ISSUE TITLE
affichage WORDLIST : mettre sous forme de tableau

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#49]
Les listes de mots comprennent parfois bcp de traductions. Il est important de les afficher en tableau pour la lisibilité. 

Exemple dans la v1 : https://doi.org/10.24397/pangloss-0001642

![image](https://user-images.githubusercontent.com/6072524/103644228-4d718880-4f56-11eb-9b5a-d1cb60ab50e0.png)

Dans l'interface v2, les traductions sont collées les unes contre les autres. 

![image](https://user-images.githubusercontent.com/6072524/103644468-b953f100-4f56-11eb-8813-74117a40bdaa.png)

Observation générale au passage : il reste du boulot pour fignoler l'affichage des listes de mots : dans la copie d'écran ci-dessus, on voit encore quelques bogues, comme les numéros en exposant (appels de notes) , alors qu'il n'y a pas de notes. Aussi, les cases "langues" ne se cochent pas quand on clique dessus (alors que l'affichage est bien mis à jour).

**Comment by alexis-michaud** [comment]
Il s'agirait de ne pas envoyer les mots (unités W) une à une, mais sous forme **d'un unique tableau**, de façon à ce qu'il y ait, pour toute la page, une colonne 'traduction en français', une pour l'anglais, etc.

C'est un changement assez profond du lecteur. Ce changement va demander aussi un développement pour l'affichage des notes, assez abondantes pour les listes de mots.

**Comment by m8nli9ht** [comment]
J'avais opté pour une mise en forme tableau simulé par des boîte "div" avec un display de type "table-cell" afin de faciliter le code et standardiser le fonctionnement entre boîtes d'options et affichage des annotations.
Je vais faire un tableau "classique" (table en HTML), mais cela va complexifier un peu le code.

**Comment by m8nli9ht** [comment]
In progress, régler le décalage lorsque des annotations ne sont pas disponibles dans toutes les langues : 
![image](https://user-images.githubusercontent.com/6407776/104623806-05a7db00-5693-11eb-8cd4-f12fd7b8fa03.png)

**Comment by m8nli9ht** [comment]
A-t-on un exemple de Wordlist avec un Word qui contienne des morphèmes ? J'en ai besoin pour mes tests !

**Comment by sguillaume** [comment]
A ma connaissance il n'y en a pas (je ne garantis pas à 100% mais presque)

**Comment by m8nli9ht** [comment]
Livré, à tester

**Comment by alexis-michaud** [comment]
Super !!

Côté intégration, serait-il possible d'avoir un peu plus de marge entre les colonnes ? 
(et une grille de tableau) 

![image](https://user-images.githubusercontent.com/6072524/110994647-5aa55c00-8379-11eb-92a0-e90a5b5aa7ba.png)
(document [ici](https://pangloss.cnrs.fr/corpus/show?lang=fr&mode=normal&oai_primary=cocoon-e0e97bb6-5722-470e-a97b-b65722770eba&oai_secondary=cocoon-95cf7a85-0329-45b0-8f7a-850329f5b0c2&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=phono&optionWordTranslations=vn%2Ben%2Bfr&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=))

(Remarque au passage : le mode "pleine largeur" fait merveille pour les documents à multiples colonnes. Une fonctionnalité qu'il valait vraiment la peine d'ajouter ! @EdouardSombie )

**Comment by sguillaume** [comment]
Honnêtement ça sera toujours plus lisible avec les grilles du tableau.
C'est important de s'y repérer facilement selon moi.

**Comment by m8nli9ht** [comment]
OK, je vais mettre des délimitations et plus d'espace.

Le ven. 12 mars 2021 à 23:13, sguillaume ***@***.***> a
écrit :

**Comment by m8nli9ht** [comment]
Traité et livré, à tester

**Comment by alexis-michaud** [comment]
Super pour le tableau (présence d'une bordure). Deux choses : 

- Qu'est-ce que vous verriez comme coloris @m8nli9ht @EdouardSombie  @sguillaume  ? Quelque chose de plus léger que du noir, non ? Un brun clair / orange très foncé ? Un gris légèrement plus foncé que le fond ?

- L'espacement entre cadre et texte est de combien de pixels ? Pour l'instant ça "colle" encore trop au bord, non ?
![image](https://user-images.githubusercontent.com/6072524/111132113-3fa13a80-8579-11eb-8bf3-b3ed2945f15b.png)

**Comment by m8nli9ht** [comment]
@EdouardSombie pour traiter ce ticket (et pensant qu'on ne pouvait plus trop te solliciter) j'ai forcé des instructions de style directement dans le player pour mettre en forme ce tableau.
Comme vu ensemble hier, il est préférable que je définisse des classes CSS pour lesquels tu mettras des instructions CSS côté Pangloss.
Pour ce ticket, as-tu besoin que je définisse une classe CSS "wordListTable" au niveau de la balise <table> ou bien la simple balise <table> te suffira pour mettre en forme ?

**Comment by m8nli9ht** [comment]
j'ai supprimé le style forcé, c'est désormais le style défini par le CSS de Pangloss qui est appliqué au tableau
