### ISSUE TITLE
différences affichage "pro" et "normal / non-pro / grand public"

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#5]
A discuter : distinction mode "pro" et mode "normal/grand public" : proposer un affichage plus "léger" pour le grand public, sans numéro de DOI, par exemple ?

@Doudou-git @sguillaume

**Comment by m8nli9ht** [comment]
on peut gérer ça très simplement en ajoutant une classe CSS à l'élément DOI (et de manière générale à tout autre élément du lecteur devant être caché en mode non-pro), à voir avec Edouard.

**Comment by alexis-michaud** [comment]
La balle passe dans le camp de @Doudou-git ?

**Comment by Doudou-git** [comment]
Je confirme.

**Comment by alexis-michaud** [comment]
Je transfère la discussion sur le site Pangloss. 

https://github.com/CNRS/Pangloss/issues/111
