### ISSUE TITLE
Type transcription

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#51]
Le type d'une transcription peut être "ortho", "phono", "phone" et "transliter" si je ne dis pas de bêtise.
Mais ça n'est pas un champ obligatoire et donc bien souvent rien n'est indiqué.
A ce moment là sur le site il y a écrit "other".
Il faudrait trouver un autre terme (et le traduire en français car c'est nommé "other" en français aussi).

Est ce que ne rien écrire mais laisser juste la case à cocher peut être une possibilité qui vous conviendrait ?

**Comment by boydmich** [comment]
Mes transcriptions M/FORM sont en fait morpho(phono)logiques; je mettrais @kindOf="morpho" si j'étais sûr que le DTD le permettait.

**Comment by m8nli9ht** [comment]
traité : autre en francais, other sinon. A livrer

**Comment by m8nli9ht** [comment]
Livré, à tester.
