### ISSUE TITLE
Mode "karaoké"

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#53]
Retour utilisateur :
"Mode karaoké :  idéalement, la phrase en cours de lecture serait
mise en valeur par un changement de couleur du fond, comme sous l'ancienne version pour que l’internaute voie tout de suite où il se trouve."

**Comment by m8nli9ht** [comment]
Traité. J'ai ajouté la classe "currentSentence" au niveau du bloc SENTENCE. Je laisse @EdouardSombie faire la mise en forme.

**Comment by m8nli9ht** [comment]
Livré, à tester.

**Comment by EdouardSombie** [comment]
Salut, c'est fait :)
La phrase en cours est encadrée.

**Comment by sguillaume** [comment]
C'est super comme ça ! Merci :)
