### ISSUE TITLE
pas d'affichage des boutons DOI dans Firefox

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#54]
Le bouton est bien actif. Quand on clique au bon endroit, le DOI s'affiche. Mais l'image (icône DOI) ne s'affiche pas. 

![image](https://user-images.githubusercontent.com/6072524/102132368-d1eb5280-3e53-11eb-82b1-be75e691f3fb.png)

**Comment by m8nli9ht** [comment]
traité et livré, à tester

**Comment by m8nli9ht** [comment]
Etrangement, l'image ne s'affiche toujours pas mais on la voit bien dans l'inspecteur de code de Firefox :
![image](https://user-images.githubusercontent.com/6407776/104736779-bf5e8480-5743-11eb-86ea-12ceb5fcdd53.png)

**Comment by m8nli9ht** [comment]
En définissant une largeur et une hauteur ça s'affiche : 
![image](https://user-images.githubusercontent.com/6407776/104736932-eae16f00-5743-11eb-9d41-fe0dc9c96a56.png)

**Comment by m8nli9ht** [comment]
@EdouardSombie combien faut-il de pixels pour width et height du coup ?

**Comment by EdouardSombie** [comment]
@m8nli9ht : pas besoin de spécifier de width ou de height

**Comment by EdouardSombie** [comment]
J'avais mis une width et une height de 0 pour remplacer l'image par un pseudo élément.
Je vais modifier le css pour que l'image s'affiche bien.

**Comment by EdouardSombie** [comment]
Réglé :)
