### ISSUE TITLE
Souci calage affichage sur phrase ou mot précis (via dièse)

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#55]
Les DOIs des phrases ne pointent pas sur les phrases concernées mais tous pointent sur le texte au niveau du titre (ça ouvre la page au niveau du titre au lieu d'ouvrir la page sur la phrase citée)

ex : https://doi.org/10.24397/pangloss-0001471#S10

**Comment by m8nli9ht** [comment]
Traité : positionnement sur l'ancre passée en URL. A livrer.

**Comment by m8nli9ht** [comment]
Livré, à tester.

**Comment by alexis-michaud** [comment]
Testé avec cet exemple : https://doi.org/10.24397/pangloss-0000658#S9

En gros : **ça marche !** 👍 

Après : 

- une mauvaise nouvelle : régression par rapport à hier soir (entre 20h et 21h le 13 janvier) : le bogue de non-lecture (pas d'affichage du lecteur Eastling), qui avait disparu hier soir (le lecteur fonctionnait à coup sûr), est réapparu. 
<img src="https://user-images.githubusercontent.com/6072524/104565077-049f8b00-564c-11eb-8b13-f88ca0bada9e.png" width="350">

- un réglage à faire : sur la page ([lien](https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-fa4ea6cd-214d-3925-8e53-031141499127&oai_secondary=cocoon-1f015e83-ed28-3100-b901-43b61bddd553&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=other&optionSentenceTranslations=en%2Bzh&optionWordTranscriptions=other&optionWordTranslations=en%2Bzh&optionMorphemeTranscriptions=other&optionMorphemeTranslations=en%2Bzh&optionNotes=#S9)) : le haut de la phrase est caché par le bandeau. 

![image](https://user-images.githubusercontent.com/6072524/104565569-bd65ca00-564c-11eb-80d2-4b25a8934924.png)

Ca c'est quelque chose qu'on avait déjà vu auparavant : voir [ici](https://github.com/CNRS/Pangloss/issues/125#issuecomment-750366718). Pour l'instant, l'affichage 'en haut' se place sur le haut de la page... qui justement est occupé par le bandeau. Il faut décaler la position verticale, de façon à ce que le haut de la phrase visée ne soit pas caché par le bandeau. C'est même mieux d'avoir une certaine marge en haut : qu'on voie la fin de la phrase précédente (ou unité W pour les listes de mots), bref 'centrer' (un tout petit peu) la phrase visée.

Résumé par Edouard (cf. [lien déjà cité ci-dessus](https://github.com/CNRS/Pangloss/issues/125#issuecomment-750366718)) : 

> il faudrait que ce soit le player qui décale le scroll de 350px vers le bas par rapport à ce qu'il fait actuellement.
> @matthew : tu peux le faire ? Ce sera plus propre que si je viens rajouter du js pour décaler les cartes vers le bas.

**Comment by m8nli9ht** [comment]
traité (sauf le "bug - encore - inconnu")

**Comment by alexis-michaud** [comment]
Le "[bogue - encore -inconnu](https://github.com/CNRS/Pangloss/issues/141)" ayant été traité ce jour (victoire !), reste seulement la question ci-dessus : 

un réglage à faire : sur la page ([lien](https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-fa4ea6cd-214d-3925-8e53-031141499127&oai_secondary=cocoon-1f015e83-ed28-3100-b901-43b61bddd553&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=other&optionSentenceTranslations=en%2Bzh&optionWordTranscriptions=other&optionWordTranslations=en%2Bzh&optionMorphemeTranscriptions=other&optionMorphemeTranslations=en%2Bzh&optionNotes=#S9)) : le haut de la phrase est caché par le bandeau. 

![image](https://user-images.githubusercontent.com/6072524/104565569-bd65ca00-564c-11eb-80d2-4b25a8934924.png)

Ca c'est quelque chose qu'on avait déjà vu auparavant : voir [ici](https://github.com/CNRS/Pangloss/issues/125#issuecomment-750366718). Pour l'instant, l'affichage 'en haut' se place sur le haut de la page... qui justement est occupé par le bandeau. Il faut décaler la position verticale, de façon à ce que le haut de la phrase visée ne soit pas caché par le bandeau. C'est même mieux d'avoir une certaine marge en haut : qu'on voie la fin de la phrase précédente (ou unité W pour les listes de mots), bref 'centrer' (un tout petit peu) la phrase visée.

Résumé par Edouard (cf. [lien déjà cité ci-dessus](https://github.com/CNRS/Pangloss/issues/125#issuecomment-750366718)) : 

> il faudrait que ce soit le player qui décale le scroll de 350px vers le bas par rapport à ce qu'il fait actuellement.
> @matthew : tu peux le faire ? Ce sera plus propre que si je viens rajouter du js pour décaler les cartes vers le bas.

**Comment by m8nli9ht** [comment]
ok je regarde ça aujourd'hui !

**Comment by alexis-michaud** [comment]
Pour refaire le point : il y a 2 choses. 

D'une part, le détail d'alignement vertical. Quand on affiche le mot 36, dans [cet exemple](https://doi.org/10.24397/pangloss-0004424#W36), il est en partie recouvert par le bandeau. Mieux vaudrait l'afficher franchement plus bas, en laissant de la marge en haut. Résultat dans Chrome (sous Windows) :
![image](https://user-images.githubusercontent.com/6072524/106397247-a2e16e00-640c-11eb-902d-df8d2a5e3646.png)

A la limite, l'affichage de la phrase souhaitée (ici la 36) commencerait un bon centimètre au-dessous du haut de la page affichée que ça serait visuellement mieux.

D'autre part, la résolution du DOI semble poser un problème intermittent. Quand on saisit un DOI, l'affichage se fait parfois (sous Windows au moins) au niveau du titre (début du document), et non à l'endroit souhaité. Il faut alors recharger la page pour accéder à l'endroit souhaité. 
Ca rappelle le souci (heureusement disparu) de page blanche du lecteur ([Pangloss #141](https://github.com/CNRS/Pangloss/issues/141)) : tout n'était pas encore en place dans le lecteur quand les contenus étaient 'envoyés', et ça restait en blanc. Le souci dans l'affichage avec un DOI avec la bonne granularité constituerait-il une régression suite aux changements du code ?
Le souci est seulement intermittent, peut-être attendre de voir si d'autres utilisateurs le rencontrent ?

**Comment by m8nli9ht** [comment]
j'ai ajusté, à tester
