### ISSUE TITLE
ne pas afficher les numéros de notes quand la case correspondante n'est pas cochée

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#56]
Pour l'instant, les numéros de notes s'affichent même quand les notes ne sont pas affichées (case 'Notes' pas cochée). Par exemple le numéro 1 en exposant dans l'image ci-dessous.
![image](https://user-images.githubusercontent.com/6072524/104568730-bb056f00-5650-11eb-8747-1ba35ac05405.png)

**Comment by m8nli9ht** [comment]
traité.

**Comment by m8nli9ht** [comment]
livré, à tester
