### ISSUE TITLE
Indiquer les mots d'emprunts

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#57]
Dans les annotations il y a la possibilité d'indiquer les mots d'emprunt.
Il avait été décidé de les mettre en italique (lors d'un projet ANR).

Ces mots ou morphèmes sont détectables par leur classe nommée "CL" : 
Par exemple : `<M class="CL">`

Il faudrait, dans cette nouvelle interface, qu'ils apparaissent aussi en italique.
C'est faisable facilement ?

Voici un exemple de texte où il y a des mots d'emprunt : 
https://pangloss.cnrs.fr/corpus/show?lang=fr&mode=pro&oai_primary=cocoon-a1adb34c-c1c2-3bc0-a0e3-b9df97c6f155&oai_secondary=cocoon-6beaee6a-42b8-3820-8180-0e9a626ec5de

**Comment by m8nli9ht** [comment]
Le parser récupère bien ces classes "CL" (niveau M ou W) donc je peux les affecter sans problème. 
Par contre, peut-on avoir des cas de mot concaténé avec des morphèmes avec ET sans classes "CL", et si oui applique-t-on l'italique au niveau du mot ?
Exemple : 
<W> 
  <M class="CL">
   <FORM>M avec CL</FORM> //sera affiché en italique
  </M>
  <M>
   <FORM>M sans CL</FORM> // ne sera pas affiché en italique
  </M>
</W>

**Comment by sguillaume** [comment]
Oui oui on peut avoir un mot composé de 3 morphèmes dont seulement 1 est étiqueté class="CL"

Du coup ne t'embête pas, ne mets en italique que le morphème étiqueté class="CL" (en tant que morphème et au sein du mot concaténé)

Ca te va ?

**Comment by m8nli9ht** [comment]
C'est parfait pour moi!
Je le ferai demain ou vendredi!

Le mer. 20 janv. 2021 à 17:10, sguillaume <notifications@github.com> a
écrit :

**Comment by sguillaume** [comment]
Prends juste en compte que le class="CL" peut être déclaré au niveau M ou au niveau W ! 

Il n'y a pas encore de cas en W directement mais ça arriver dans les semaines qui viennent !

**Comment by m8nli9ht** [comment]
Traité et livré. 
J'ai rajouté une classe css "CL" au niveau W et M quand pertinent, malheureusement, elle est ignorée dans Pangloss ; je pense donc que Edouard devrait nous débloquer.

**Comment by m8nli9ht** [comment]
Nous étions restés sur un affichage en italique, mais la référence au ticket #64 mentionne des petites capitales. Que choisit-on ?

**Comment by sguillaume** [comment]
Les petites capitales étaient pour les gloses si je ne dis pas de bêtises.
Là il s'agirait d'indiquer les mots d'emprunt.

Lors du projet ils avaient voté pour l'affichage des mots d'emprunt en italique.
(Je suppose que si un jour ça doit changer, ça ne sera pas trop compliqué ?)

Je dirais donc italique tel que ça a été pensé à l'origine par les seules personnes qui utilisent cela !

**Comment by m8nli9ht** [comment]
J'ai fait en sorte de récupérer les classes (CL, ...) depuis le fichier annotation. Il faut définir le style côté intégration car les instructions CSS définies côté player sont ignorées (passage de relais pour l'intégration avec Edouard ?)

**Comment by m8nli9ht** [comment]
Vu avec Edouard hier, ticket à transférer côté Pangloss avec cette indication pour Edouard : Une classe "CL" a été créée pour les morphèmes, il faut lui attribuer une instruction CSS pour que la font soit en italique
