### ISSUE TITLE
Bug affichage phrases de traduction

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#58]
Il y a une concaténation des mots (W) pour former une phrase de traduction (qui apparait sous "autre") alors qu'il existe bien des traductions au niveau de la phrase (S). Du coup, une suite de gloses apparait comme traduction de phrase (en plus des vraies traduction de phrases).
 
Il faut qu'il y ait concaténation au niveau du mot que s'il n'y a aucune traduction au niveau de la phrase (quelle que soit la langue de traduction. Une seule au niveau de la phrase doit suffire pour ne jamais concatener au niveau du mot)
 
cf : https://pangloss.cnrs.fr/corpus/show?lang=fr&mode=pro&oai_primary=cocoon-6af04a0f-aab9-3fe9-a35e-ffe556e9c9f8&oai_secondary=cocoon-3ce3ccde-a310-3e84-be2b-eecc86474000

**Comment by m8nli9ht** [comment]
traité avec la #59
