### ISSUE TITLE
intégration lecteur Eastling au site de Cocoon ?

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#6]
Un affichage (simplifié) des documents EASTling depuis Cocoon est en place. Voir [cette page](https://cocoon.huma-num.fr/exist/crdo/meta/cocoon-861c4050-8ef0-3821-bbbc-a535860ed807) :
![image](https://user-images.githubusercontent.com/6072524/82056744-a8eabf80-96c2-11ea-9199-43cd5b42068c.png)
 
Y compris un [Code d'intégration dans une page web](<iframe height="320" src="https://cocoon.huma-num.fr/exist/rest/db/www/xql/cocoon_iframe.xql?id=cocoon-861c4050-8ef0-3821-bbbc-a535860ed807" width="600"></iframe>).

Comment aller de l'avant : intégrer un lecteur EASTling plus complet à Cocoon ? Proposer plusieurs lecteurs possibles ? Dans ce dernier cas : planifier des améliorations au lecteur EASTling dans Cocoon ?

**Comment by m8nli9ht** [comment]
quand je clique sur le lien indiqué, je ne vois pas le lecteur :
![image](https://user-images.githubusercontent.com/6407776/96493084-d248e200-1244-11eb-88a9-7ea413aed1ae.png)

**Comment by alexis-michaud** [comment]
@m8nli9ht Il faut cliquer sur le lien en bas à droite sur la copie d'écran montrée ci-dessus ("Annotations : Les abeilles..."). On voit alors le manuscrit.
![image](https://user-images.githubusercontent.com/6072524/96495655-6b2d2c80-1248-11eb-93b8-5e212ad7b714.png)

**Comment by alexis-michaud** [comment]
Ca fait d'ailleurs partie des améliorations à envisager pour le site Cocoon : que les utilisateurs parviennent à s'y retrouver pour les documents qui possèdent une dimension "image", comme celui-ci. Pour l'instant, la double mention à l'identique  n'encourage pas trop à cliquer dessus, ça vous a un air de page web bien déjantée :-D
![image](https://user-images.githubusercontent.com/6072524/96495826-b0e9f500-1248-11eb-84b9-a85c0d7b1a2a.png)

**Comment by alexis-michaud** [comment]
@m8nli9ht : poursuivre la coordination avec l'équipe de Cocoon, et voir si Eastling rendrait des services pour le site Cocoon. 

A voir tranquillement dans les premières semaines/premiers mois de 2021, une fois passée la phase actuelle de "sprints" successifs de finalisation de la v2 ?

**Comment by m8nli9ht** [comment]
peut-être s'inspirer du travail d'Edouard pour intégrer dans Cocoon comme c'est fait dans Pangloss ?

**Comment by alexis-michaud** [comment]
Dans l'immédiat, il semble que la préférence de l'équipe Cocoon aille vers la poursuite d'un fonctionnement autonome du site Cocoon, sans dépendre d'outils externes (pour faciliter la maintenance de moyen/long terme).
