### ISSUE TITLE
modifier à la volée http en https dans la requête à Cocoon

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#60]
L'interface Pangloss s'affiche comme étant un site **Non sécurisé** : 

![image](https://user-images.githubusercontent.com/6072524/105544591-6b334180-5cfb-11eb-9a98-56a7727d8f3e.png)

C'est paradoxal que le site soit indiqué en "Non sécurisé" alors que le protocole est bien https ("S" comme "Sécurisé") et non http. @EdouardSombie explique que ça tient au fait que les téléchargements se font auprès de Cocoon, qui, lui, est en http pour les ressources. Par exemple, lien vers un fichier XML :
http://cocoon.huma-num.fr/data/adamou/masters/versions/crdo-RMN-ROM3_v2.xml

C'est ce qui rejaillit sur la classification de l'interface Pangloss comme étant non sécurisée.

C'est ennuyeux pour les visiteurs, qui se trouvent sur un site suspect puisque non sécurisé, et peuvent être tentés d'aller voir ailleurs. 

Cocoon (dont l'interface est maintenant passée en https) pourrait envisager de passer en https pour toutes les connexions. Ca paraît souhaitable à terme, mais ça peut prendre un certain temps. Or il est important que Pangloss propose un affichage rassurant ("Sécurisé") : ça a une vraie importance pour les publics très divers dont on souhaite encourager les visites. 

@EdouardSombie indique : 

> Il faudrait que le player modifie à la volée l'url de ses ressources en remplaçant le http par https
> Une fois cela fait, il ne devrait plus y avoir de souci.

**Comment by alexis-michaud** [comment]
Indication dans la console de Chrome concernant le statut non sécurisé attribué à la page : il faut passer en https aussi pour récupérer le fichier mp3, semble-t-il ?

`Mixed Content: The page at 'https://pangloss.cnrs.fr/corpus/show?lang=en&mode=pro&oai_primary=cocoon-d7422cbf-af6d-3abd-a14e-256db16c4b3e&oai_secondary=cocoon-808ed143-df51-3954-bf98-74d17bd3bb2e&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&optionSentenceTranscriptions=phono&optionSentenceTranslations=&optionTextTranscriptions=&optionTextTranslations=&optionWordTranscriptions=&optionWordTranslations=' was loaded over HTTPS, but requested an insecure audio file 'http://cocoon.huma-num.fr/data/jacques/hist-25-cWXCWz.mp3'. This content should also be served over HTTPS.`

![image](https://user-images.githubusercontent.com/6072524/106204504-5c4a0480-61bd-11eb-9f58-f94c608d25b8.png)

**Comment by m8nli9ht** [comment]
Pourquoi ne pas faire cela directement en base de données ?

**Comment by m8nli9ht** [comment]
Ok traité et livré, à vérifier.

**Comment by alexis-michaud** [comment]
Excellent !! Ca marche : voilà le site passé en mode Sécurisé. 
![image](https://user-images.githubusercontent.com/6072524/106879580-9c3c4a80-66db-11eb-9ba1-9fd2058834e8.png)
👍
