### ISSUE TITLE
Lecture en continu vs écoute d'une seule phrase

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#62]
Plusieurs personnes ont demandé si on pouvait remettre la possibilité de choisir de lire tout le fichier audio ou alors uniquement une seule phrase (avant, il y avait une petite case à cocher à côté du lecteur audio pour choisir "lecture en continu" ou non).
Pour les linguistes ça a l'air d'être assez précieux de pouvoir écouter plusieurs fois d'affilés uniquement une phrase (et de ne pas avoir la lecture qui continue sur la suivante).

On pourrait remettre cette option ?

**Comment by sguillaume** [comment]
On m'a encore relancé à ce propos (encore une autre personne).
Est ce que ça peut être fait dans les priorités ?

(avec la phrase que l'on écoute qui s'affiche un peu plus bas pour permettre d'avoir le contexte c'est à dire de pouvoir lire la phrase du dessus et du dessous. Or actuellement, la phrase en cours est trop haute et cache celle du dessus)

**Comment by m8nli9ht** [comment]
livré, à tester.
Dorénavant, lorsqu'on clique sur le bouton play d'une phrase ou d'un mot dans le cas de wordlist, seul cette phrase ou mot est lu(e). Pour la lecture en continu, c'est le bouton play du lecteur principal qu'il faudra utiliser.

**Comment by alexis-michaud** [comment]
@sguillaume le ticket peut maintenant être fermé ?

**Comment by sguillaume** [comment]
En fait il faudrait qu'il y ait une case qui permette de choisir si on veut la lecture en continu ou non.

Parce que maintenant, on ne peut plus écouter le texte en continu à partir d'une phrase précise.
Soit on clique sur play sur le lecteur et on a la lecture en continu, soit on clique sur une phrase et on a uniquement la lecture de la phrase.
Si jamais quelqu'un veut reprendre la lecture du milieu du texte il ne peut pas (à moins de cliquer sur chaque phrase pour les écouter. Ou de tout réécouter depuis le début du texte).

Je ne sais pas si je suis claire dans mon explication.

En gros, il faudrait une case à cocher pour choisir "lecture en continu" ou non.
Dans tous les cas (que la case soit cochée ou non) si on clique sur le lecteur on a une lecture du fichier en entier
- Si on coche lecture en continu alors quand on clique sur une phrase particulière, ça lance la lecture à partir de cette phrase et jusqu'à la fin du texte
- Si on ne coche pas "lecture en continu" alors quand on clique sur une phrase précise, on ne lance que l'écoute de cette phrase.

**Comment by m8nli9ht** [comment]
ok, traité et livré, à tester (j'en ai profité pour repositionner les ancres dans les wordlists)

**Comment by sguillaume** [comment]
Cool c'est exactement ça ! :)
Merci !

Est ce que c'est possible de mettre la case "Lecture en continu" au dessus de "Options d'affichage" ?
Car ça n'est pas une option d'affichage et c'est plutôt lié au lecteur (et comme ça ça sera plus proche du lecteur)

**Comment by m8nli9ht** [comment]
Ca m'embête un peu car c'est une option et il faudrait rester cohérent avec l'organisation de la page (toutes les options sont dans le même bloc). Pourquoi ne pas simplement changer le libellé du bloc "Options d'affichage" par "Options de lecture" ou "Options" tout court ?

**Comment by sguillaume** [comment]
OK je comprends.
Et si on met cette option un peu en dessous des autres histoire de la distinguer (option pour les textes vs option pour l'audio) ?

**Comment by m8nli9ht** [comment]
oui on peut aussi, je vais proposer quelque chose !

**Comment by m8nli9ht** [comment]
c'est fait !

**Comment by sguillaume** [comment]
C'est parfait !
Est ce qu'on peut mettre la case à cocher sur la même ligne que l'intitulé "Lecture en continu" ?
(ça laisserait un peu plus d'espace avec les options du dessous qui sont pour le texte).
C'est déjà super comme ça en tout cas !

**Comment by m8nli9ht** [comment]
c'est fait, par contre j'ai mis un composant (SLIDER) de mon framework qui est différent de celui du framework de Pangloss. @EdouardSombie t'en penses quoi ?

**Comment by sguillaume** [comment]
C'est possible un espace un chouilla plus grand entre cette ligne et celle des transcriptions (celle du dessous) ?
(oui oui j'abuse je sais :p)

**Comment by m8nli9ht** [comment]
oui possible mais je pense que c'est pour Edouard du coup !

**Comment by m8nli9ht** [comment]
du coup on peut clôturer ce ticket ?

**Comment by sguillaume** [comment]
On pourrait juste remettre la case à cocher ? (ça parait plus clair coché / pas coché)

Sinon oui on peut clôturer après !

**Comment by m8nli9ht** [comment]
OK
