### ISSUE TITLE
Affichage de toutes les ressources secondaires

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#65]
Ca serait bien de pouvoir avoir accès à la même page (avec les mêmes options d'affichage) quelle que soit la ressource secondaire à laquelle on veut accéder.

Je m'explique.
Chaque ressource secondaire est liée à une ressource primaire.
Il faudrait que l'url qui affiche ces ressources https://pangloss.cnrs.fr/corpus/show?&oai_primary=OAI_PRIMAIRE&oai_secondary=OAI_SECONDAIRE
ramène sur la même page quel que soit l'OAI_SECONDAIRE que l'on souhaite afficher et qui est lié à l'OAI_PRIMAIRE.

Ca marche quand la ressource secondaire est une ressource "affichable" telle que annotations xml ou pdf mais ça ne marche pas avec les EGG.
Il faudrait que les url avec oai d'un EGG ouvre aussi la même page avec le son (et les annotations s'ils y en a).

ex: avec l'OAI_PRIMAIRE = cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2
Cette ressource primaire a :
- une annotations XML (OAI_SECONDAIRE = cocoon-b8f0c77a-b602-335c-9c7b-0dddc656706f)
- un fichier EGG (OAI_SECONDAIRE = cocoon-22cf60f0-3b08-4cb6-8f60-f03b08acb61a)

Ca donnerait la même page quelle que soit l'une de ces 3 urls:

(son uniquement) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2

(son et annotation) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2&oai_secondary=cocoon-b8f0c77a-b602-335c-9c7b-0dddc656706f

(son et EGG) -> https://pangloss.cnrs.fr/corpus/show?oai_primary=cocoon-ecaff366-c3d1-341b-b725-78bfbc7bc7e2&oai_secondary=cocoon-22cf60f0-3b08-4cb6-8f60-f03b08acb61a

Le problème est quand on utilise le DOI d'un EGG. Ca renvoit à une url du type oai_primaire = oai du son et oai_secondaire = oai de l'EGG
Et là ça ouvre une page où même s'il y a des annotations liées au même son, elle n'apparaissent pas. Seul le son apparait. Ce qui est dommage.

**Comment by m8nli9ht** [comment]
le player ne gère pas les encarts "Téléchargement" et "Métadonnées" --> à faire côté Pangloss
