### ISSUE TITLE
Mise en évidence des mots survolés sur les documents avec manuscrit

### ISSUE THREAD

**Issue by m8nli9ht** [CNRS/eastlingplayer#66]
- cadre sur l'image
- classe CSS sur le mot

**Comment by m8nli9ht** [comment]
ok traité et livré

**Comment by m8nli9ht** [comment]
Le survol d'un bloc WORD devrait surligner l'aire dans l'image mais cela ne fonctionne pas côté Pangloss
![image](https://user-images.githubusercontent.com/6407776/112483932-c4f6cd00-8d79-11eb-8c68-cc00a5826bb3.png)

**Comment by alexis-michaud** [comment]
Maintenant ça marche impecc'
![image](https://user-images.githubusercontent.com/6072524/189317352-7096117f-d09b-4d31-ad81-9724e1689674.png)

et le ticket pourrait donc être fermé, n'est-ce pas ? @m8nli9ht
