### ISSUE TITLE
Bug pas d'affichage des pdf

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#67]
Les pdf ne s'affichent pas.
Ils devraient s'afficher normalement sous le lecteur audio (il me semble pourtant que ça marchait à un moment mais je ne peux pas le certifier).

Voici un exemple d'url avec pdf : 

https://pangloss.cnrs.fr/corpus/show?lang=fr&mode=pro&oai_primary=cocoon-41ab928e-b090-360b-9f4d-43dad8a11421&oai_secondary=cocoon-b62a5195-ef88-3f32-835a-f8d6b3bcf39c&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=&optionWordTranslations=&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=&continuousPlay=false

**Comment by m8nli9ht** [comment]
ok je regarde aujourd'hui

**Comment by m8nli9ht** [comment]
c'est corrigé.
