### ISSUE TITLE
Problème d'affichage de caractères

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#73]
Il y a des textes dont les caractères ne s'affichent pas lors de la consultation des ressources comme celle ci : https://doi.org/10.24397/pangloss-0004157

Parfois les caractères s'affichent bien mais pas très joliment : https://doi.org/10.24397/pangloss-0000586

Il faudrait trouver une police adaptée.

**Comment by alexis-michaud** [comment]
Ce ticket #73 vient opportunément faire écho au #72 ouvert tout récemment.
Maintenant qu'on rouvre le dossier et qu'on repart de l'avant avec une 2e vague d'améliorations, on se demande comment on a pu vivre tout ce temps avec des polices phonétiques pas super-bien choisies :smiley::smiley:
Aussi @EdouardSombie

**Comment by alexis-michaud** [comment]
réglé, bien joué @EdouardSombie !
