### ISSUE TITLE
Petit formatage des annotations à l'affichage

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#76]
Lorsque le texte est transcrit ou traduit intégralement (en un bloc et non juste au niveau des phrases) donc au niveau de TEXT/FORM ou de TEXT/TRANSL (cela correspond aux cases à cocher "Transcription du texte" ou "Traduction du texte" lorsqu'il y en a une),
il faudrait que le bloc traduit ou transcrit soit affiché avec le même formatage que dans le xml.
C'est à dire détecter et conserver les sauts de lignes s'il y en a (car sinon le texte est très difficile à lire).

**Comment by m8nli9ht** [comment]
Traité et livré, à tester

**Comment by sguillaume** [comment]
Génial !
J'ai testé 2 textes c'est nickel
