### ISSUE TITLE
La case à cocher des notes ne s'affiche pas quand il n'existe d'éléments <NOTE> qu'au niveau du texte entier

### ISSUE THREAD

**Issue by sguillaume** [CNRS/eastlingplayer#77]
Dans ce texte dendi, il y a des notes (balise NOTE) mais la case à cocher permettant de les afficher n'apparait pas : 
https://doi.org/10.24397/pangloss-0008191

Alors que dans celui ci du na de Yongning, il y a des notes au même niveau et la case à cocher s'affiche pour des notes au même niveau (niveau TEXT) : 
https://doi.org/10.24397/pangloss-0004342

Nous n'arrivons pas à voir quelle est la différence dans le XML qui fait que dans un cas la case permettant de visualiser les notes s'affiche et pas dans l'autre cas.

**Comment by alexis-michaud** [comment]
C'est parce que la note se situe juste sous la racine : elle concerne le texte entier. 

```
<TEXT id="nt_dendi_karimama_68_A_conte1" xml:lang="ddn">
<HEADER/>
(...)
<NOTE xml:lang="fr" message=" Les contes de ce corpus dendi, issus d’une numérisation « de sauvetage » et d’une étude de recherche menée maintenant il y a plus de 50 ans n’ont pu bénéficier d'une révision de la transcription, en particulier celle des tons, en raison de contraintes liés à cette enquête sur le terrain. Si vous êtes en mesure de fournir des informations pour une vérification de la transcription d’un ou plusieurs de ces contes, merci d'écrire à : nicole.tersis@cnrs.fr et/ou lacito.direction@cnrs.fr "/>

<S> <!début de la première phrase> (...)
```

Les notes ne sont affichées que si elles se trouvent à l'intérieur d'une balise `<S>` (ou aussi `<W>`, ou `<M>` : à vérifier).

Un ticket à ce sujet a été ouvert dans le dépôt "Pangloss website", ici : 
https://github.com/CNRS-LACITO/eastlingplayer/issues/79

**Comment by alexis-michaud** [comment]
Si la case à cocher "NOTES" s'affiche bien pour le texte en na de Yongning ([ici](https://doi.org/10.24397/pangloss-0004342)), c'est parce qu'il y a, dans ce document-là, outre des notes "sous la racine" (au niveau `<TEXT>`), des notes au niveau de la phrase, du mot... Exemple ci-dessous.
![image](https://github.com/CNRS-LACITO/eastlingplayer/assets/6072524/2a4c8f9b-2697-43f0-83c5-2efc5f4f69bb)

Cet exemple permet de s'assurer que le souci à régler concerne uniquement l'affichage de la case à cocher "NOTES". 
![image](https://github.com/CNRS-LACITO/eastlingplayer/assets/6072524/0b5936d4-59ad-4a70-b0f0-23ad655a81cd)
Dès lors que ces cases apparaissent, on obtient toutes les notes du texte en un seul clic : les notes à tous les niveaux (TEXT, S, et (à confirmer) W et M).

**Comment by alexis-michaud** [comment]
En lien aussi avec [le ticket CNRS-LACITO/eastlingplayer#78 du dépôt "Pangloss website"](https://github.com/CNRS-LACITO/eastlingplayer/issues/78) : numérotation des notes concernant le texte entier.

**Comment by alexis-michaud** [comment]
Aussi, un petit point qui concerne encore les notes : 

Quand le document est de type LISTE DE MOTS (`WORDLIST`), le numéro de note n'est pas en exposant, et il est collé au contenu de la note. Exemple ([ici](https://pangloss.cnrs.fr/corpus/show?corpus=Yongning_Na&mode=pro&oai_primary=cocoon-5206b066-e8e7-32d5-acdc-934f3387cb2e&oai_secondary=cocoon-bda1f654-d6bf-381a-9776-d148626cbcd5&lang=fr&optionTextTranscriptions=&optionTextTranslations=&optionSentenceTranscriptions=&optionSentenceTranslations=&optionWordTranscriptions=autre&optionWordTranslations=&optionMorphemeTranscriptions=&optionMorphemeTranslations=&optionNotes=en&continuousPlay=false&fullWidth=true)) : 

![image](https://github.com/CNRS-LACITO/eastlingplayer/assets/6072524/305e9d17-8bb9-435a-908f-cd759687b936)

![image](https://github.com/CNRS-LACITO/eastlingplayer/assets/6072524/0c339914-8515-40e1-a702-c240a3fb06f1)

Il faudrait faire comme pour les notes des documents de type TEXT : numéro en exposant, et séparé du texte par un espace.

**Comment by m8nli9ht** [comment]
le problème est à priori dans le parser, analyse en cours

**Comment by m8nli9ht** [comment]
Traité et livré, à tester

**Comment by sguillaume** [comment]
Parfait les notes s'affichent ! 
Merci.
