### ISSUE TITLE
Affichage des notes au niveau du document entier (TEXT ou WORDLIST)

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#79]
Des échanges récents avec des contributrices & contributeurs confirment l'importance des notes. Elles sont une composante traditionnelle de l'appareil philologique déployé autour des ressources primaires, et elles rendent des services. Leur affichage dans l'interface (et dans [les exports qui seront proposés : LaTeX, livrets PDF](https://github.com/CNRS-LACITO/Pangloss_website/issues/251)...) mérite d'être encore peaufiné.

Certains documents XML d'annotation contiennent une ou plusieurs notes qui concernent le document entier, plutôt qu'une phrase en particulier. Il s'agit des notes qui sont placées directement sous la racine `<TEXT>` ou `<WORDLIST>`, plutôt qu'à l'intérieur d'une balise `<S>` ou `<W>` ou `<M>`.

Par exemple : [ce document](https://doi.org/10.24397/pangloss-0004969) (ici [en XML](https://cocoon.huma-num.fr/data/michaud/masters/crdo-VIE_CFIN_F1.xml)) contient une longue, longue note qui contient tous les _time codes_ des syllabes-cible de l'étude. 

```
<NOTE xml:lang="en" message="Here are time codes for carrier sentences (plain numbers) and target items (with 'a' suffix for one reading condition and with 'b'c suffix for the other), exported from Sound Forge:
Name Start End Length
-------------------------- ------------- ------------- -------------
1 00:00:09.311 00:00:13.630 00:00:04.318 1a 
...
</NOTE>
```

Pour l'instant, rien dans l'affichage en ligne ne signale l'existence de cette note : pas de case "NOTES" à cocher (il s'agirait en l'occurrence d'une case concernant le texte entier, qui porterait mention de la langue de la note : ici, de l'anglais).

![image](https://github.com/CNRS-LACITO/Pangloss_website/assets/6072524/b261c784-c499-41c8-acbd-d3f3c625fd08)

À transférer sur le dépôt du lecteur Eastling ? @sguillaume @m8nli9ht

**Comment by m8nli9ht** [comment]
Je viens de corriger. Par contre le FTP est indisponible pour livrer le build. En attente.

**Comment by m8nli9ht** [comment]
Livré, à tester

**Comment by alexis-michaud** [comment]
Bien joué !
![image](https://github.com/CNRS-LACITO/eastlingplayer/assets/6072524/d86b0be9-b479-4aaf-8ae3-9deb5e7b690f)
:+1:
