### ISSUE TITLE
bouton "Transcription du texte entier" ("Whole text transcription")

### ISSUE THREAD

**Issue by alexis-michaud** [CNRS/eastlingplayer#8]
Le bouton "Transcription du texte entier" ("Whole text transcription") est inerte pour des documents qui n'ont pas dans le XML de champ \<FORM\> au niveau du texte entier, comme celui-ci :
 corpus/show?mode=pro&oai_primary=cocoon-16586ac3-6bba-3c3f-86d9-0b9f877c605a&oai_secondary=cocoon-ec43abba-bd90-3970-a9a3-1f69ddbd75c0&optionWords=true&optionNotes=true&optionTranscriptions=%2Bphone&optionTranslations=%2Bcn%2Bfr&optionGlosses=%2Bcn%2Bfr%2Ben&optionWholeTranscriptions=false&optionWholeTranslations=%2Bcn

Ce qu'il faut faire dans ces cas-là, c'est concaténer le contenu de la balise \<FORM\> au niveau phrase (en proposant, s'il y a 2 attributs, par exemple 1 pour transcription orthographique et 1 pour transcription phonétique, de choisir entre l'un et l'autre), et d'afficher le produit de cette concaténation. C'est ainsi que ça marchait sur l'affichage v1. 

(Sauf que ça ne marche plus au jour d'aujourd'hui, haha... mais tu vois l'idée)

On laisse un retour chariot après chaque unité PHRASE. Par exemple, pour ce texte :
ə˧bɛ˧-ʂɯ˩bɛ˩, 
ə˧pʰʋ˧ nɛ˩ ə˧dzɤ˧ ɲi˩-kʋ˧˥ ndʑju˩ mi˧-ʝi˩-tsɤ˧˥.
ə˧kjɛ˧, ʝi˧ʈʂɯ˩ bɛ˧, zy˧˥ mɤ˩-ndʑju˩ mi˧-ʝi˩-tsɤ˧˥.

etc.

**Comment by m8nli9ht** [comment]
vu, je traite également dans le prochain sprint

**Comment by m8nli9ht** [comment]
Traité pour les documents sans balise TEXT->FORM.
Afin de finaliser les tests, possible d'avoir un exemple de document AVEC la balise TEXT->FORM renseignée ? Merci d'avance

**Comment by alexis-michaud** [comment]
Voici voilà ! 
https://pangloss.cnrs.fr/corpus/show_text.php?id=cocoon-8c729359-ac07-46bd-b293-59ac07b6bdb5&idref=cocoon-0dd84155-14a7-4115-9841-5514a781159a

"Mother's Birthday"
cocoon-0dd84155-14a7-4115-9841-5514a781159a

(c'est du na, en orthographe)

```
<FORM>Ama bbu Jjogee
Nya nee ceehan nosigu gi nya ama bbu eshae khuae ddeelee ruaq bbi mae.
Tiq, nya ama jjo noq amuggomi tee kheugu  jjo niq zimu. Kheugu jjo jjo, tiq, nya ama jjo muq jiehin teevu niq zimu. Muq jieq teelee niq jjo, tiq, nya ama bbu ama, nya axxi, axxi bbu amu jjo ssomu mejjo niq zimu. Tiq, wodda teezhae gho jjo ddeelee jjoq niq ziq,  ddeelee jjoq jjo, tiq, honlhi la ggu see gge gha, hin nee dduq gi sso leshi niq zimu. Tiq, leshi gua jjo, tiq, axxi ddeeq teevu jjo ssomu ddeelee mejjo niq ssei. Tiq gua, nya axxi la teejie nee lewuawua sso, ama lexxi sso, axxi ddeeq teevu gi gi niq zimu.
Ceekhae jjo osigu ruaeq ddeeda sheri gohin niq bi ruaeq gaeq jjo tiq. Ddeeni jjo, nya ama la teejie jjo lo yi hee niq zimu. Lo yi hee jjo, teejie lo yi teekua gho, teejie raerae sso: "Abobo, osigu jjo aezei niq ae?   Osigu bbu sheri sseini niq meneu meneu!" bi, lechala jjo tiq.
Teeggi teeni teejie lehee nya, ddeeda onbbu ami gi sheri muddo hee niq ziq. Teeni ama jjo nya axxi teevu gi: "Ami hrami, nya jjoq teeni jjo sseini niq ssei ae?" bi jjo tiq.
Nya axxi nee: "O, nya ddeeshuddu bbi mae" bi jjo tiq. "No jjoq teeni jjo muzzei ku teeni niq bbaq" bi.  "O meni meni mae, zzeilee ku ddeeni niq," bi. "O meni meni meni o, ooo! Khazzei khaeq ddeeni jjo no lejjo teeni niq!" bi niq ziq.
Tiq, teejie uaq teeggi ddeeni le'uo lo yi hee jjo nya, ama nee, tiq, teejie gi: "O, nya ami nya sseini lejjo niq tee meneu ziq, tiq, khazzei khaeq ddeeni noq lejjo niq ziq" bi jjo tiq.  
Teebbu zzhu teejie nee: "Ze yi, ze yi, ze yi, osigu wua, tiq, khacee khazzei khaeq jjo, tiq, khacee nobbu sheri zhe;  osigu wua bbu khazzei khaeq teelee nobbusheri zhe ji!" bi tiq, tee niq bi niq ziq, teejie ruaeq leraerae niq ziq.
Nya ama jjo, tiq, ggi jjo noq zzhu ruaeq jjahin ddeevu jjo niq ssei. Zzhu teevu jjo, tiq, Yidali bi teekua gho lecee niq, tiq, tee jjo ruaeq daego gguq guhin niq, tiq, daego ddeelee latae leggu ruaeq ruq jjo tiq. Nya ama la teessi ruaeq hohin,  ruaeq zzhu niq.
Tee gi hrami: "Gisso Lhaco, nobbu jjogee jjo sseini niq ae?" bi ziq.  
Tee nee: "Aezi a, nya ami nee nya gi ruaq jjo nyabbu lejjohin teeni jjo khazzei khaeq teeni niq ziq."
Tiq, tee nee jjo: "O, tiq, khazzei khaeq teeni jjo sseini niq ae? Tiq, nya khazzei khaeq teeni jjo memesi, tiq, nobbu jjogee jjo sseini niq tee, ossi memesi, tiq, khani sso tee noq qiezhu zo ae?" bi, tee niq ruaq jjo tiq.
Tiq, zzhu teevu nee teehan jjo daego ddeelee gguq ji niq ziq. Daego ruaeq nuxie keeq, ruaeq ruq keeq ddeelee gguq sso, tiq: "O, Gisso Lhaco, ceeni jjo nobbu sheri zhe ji, ossi ceeni qiezhu bbi" bi, tee niq lerua jjo tiq. 
Nya ama bi, noq ruaeq numi gho lefu sso, legaedo sso, noq lengu ji niq ziq. Noq adda ami noq boq nee, jjo tiq, tee niq sso lejjo jjo, tiq, noq sseini lejjo ddia gha lemupae keeq, daeshi noq bbu zzhu teevu nee tee niq sso noq boq nee jjaq yi, tiq, noq bbu sheri latae noq gha leqiezhu ghaq jjo, tiq, noq dduaeq fu sso, lengu ji niq ziq.</FORM>
```

**Comment by m8nli9ht** [comment]
Merci. J'ai testé et tout marche ! J'ai envoyé le Build à Edouard, je versionne ces modifs lorsque vous les aurez validées .

**Comment by m8nli9ht** [comment]
Edouard a-t-il mis à jour le dernier build ? Si oui, pouvez-vous tester et me faire un retour sur ce point ?

**Comment by EdouardSombie** [comment]
Salut, je pense que c'est le dernier build qui est en ligne.
C'est celui envoyé le 22/10

**Comment by m8nli9ht** [comment]
> 
> 
> Salut, je pense que c'est le dernier build qui est en ligne.
> C'est celui envoyé le 22/10

Top, @alexis-michaud tu pourras tester cette correction ?

**Comment by alexis-michaud** [comment]
Alors, en faisant le test avec un autre document, il semble qu'il reste un peu de travail : 

C'est le texte "Le mariage de la soeur"
oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee

Quand on pousse le bouton "Transcription texte entier", il ne se passe rien. 

En revanche, quand on recharge la page après avoir pressé le bouton, la transcription s'affiche bien. Réglages : 
&optionGlosses=&optionNotes=false&optionTranscriptions=%2Bphono%2Bortho%2Bphonetic&optionTranslations=%2Bfr%2Ben&optionWholeTranscriptions=true&optionWholeTranslations=&optionWords=false

(Pareil pour version fr et version en)

Quand le texte est bien affiché et qu'on décoche, par contre, ça marche, la transcription texte entier disparaît.

Est-ce que le problème n'a lieu que sur mon ordinateur à cause d'un cache mal vidé ? (je pense pourtant avoir fait ce qu'il fallait)

**Comment by m8nli9ht** [comment]
Il ne se passe rien sûrement si aucune transcription n'est cochée !

Si tu coches transcription=ortho et whole transcription=on, ça marche.

Le player ne peut pas deviner pour quelle type de transcription (si il en existe plusieurs dans le document) il faut tout afficher...

**Comment by alexis-michaud** [comment]
ça ne marche pas non plus (sur mon ordinateur) quand "phono" est coché

corpus/show?lang=fr&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&optionGlosses=&optionNotes=false&optionTranscriptions=%2Bphono&optionTranslations=%2Bfr%2Ben&optionWholeTranscriptions=true&optionWholeTranslations=&optionWords=false

**Comment by alexis-michaud** [comment]
ni quand "ortho" est coché

corpus/show?lang=fr&oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee&optionGlosses=&optionNotes=false&optionTranscriptions=%2Bphono%2Bortho&optionTranslations=%2Bfr%2Ben&optionWholeTranscriptions=true&optionWholeTranslations=&optionWords=false

Par contre quand je recharge la page (donc avec la même URL, contenant les mêmes réglages), ça marche

**Comment by m8nli9ht** [comment]
Pourrais-tu essayer depuis cette page et me dire si c'est toujours le même résultat ?
https://eastling.huma-num.fr/player/?oai_primary=cocoon-3dd9341b-647a-33d3-b0fd-2b0ab0e7f638&oai_secondary=cocoon-46ae2130-95ad-342d-9606-ef3d47594bee

**Comment by alexis-michaud** [comment]
Oui, c'est le même résultat sur mon ordinateur. 
![image](https://user-images.githubusercontent.com/6072524/97873277-aedb6800-1d17-11eb-9361-7478f9bf3f17.png)

**Comment by m8nli9ht** [comment]
Les transcriptions completes sont disponibles en ortho pour ce texte, pas en phono

**Comment by alexis-michaud** [comment]
Bon, j'ai répondu trop vite :sweat:
**Faisons le point soigneusement.** 

Ce texte a ceci d'intéressant qu'il y a une transcription phonologique ("savante") et une transcription orthographique. 

Première phrase (unité `<S>`):
```
<FORM kindOf="phono">ə˧ʝi˧-ʂɯ˥ʝi˩ ◊ -dʑo˩ … ◊ ə˩-gi˩!</FORM>
<FORM kindOf="ortho">Eyishei jjo … aeggi! …</FORM>
```

Affichage du texte entier : attention, 2 cas de figure : 

- le contenu désiré existe déjà sous une forme fournie par le déposant : 
par exemple, ici, pour la forme orthographique : 
`<FORM kindOf="ortho">Eyishei jjo … aeggi! … tee niq yi guq zimu. Tiq, mussinimi nigu jjo zimu. Tiq, amu yihin jjo sso niq zimu. Tiq, sso jjo, tiq, kushae hee zimu. Tiq, jjinami wo ddeesoku teezzee zimu. Qiddi hee zimu. Tiq, ggomi jjo, tiq, awo jjo zimu. Tiq, amu lemecee jjo, tiq, hin gi gi zimu. Tiq, hin gi gi seiq jjo, tiq, ri teeq zimu. Ri teeq ha zzi wodo jjo, tiq, gezzee zimu. Gezzee jjo, tiq, ddeehin jjo ggezze zzeeq keeq, jiehin muzze zzeeq. Tiq, ddeeda gezzee: ddeehin ddeezzee ddeezzee ddeezzee ddeezzee nee teegho teejjo, maegho teegho teejjo, tiq, tee amu tee qiddi lecee zimu. `
etc.
Dans ce cas on affiche le contenu de la balise en question.
Ca, ça fonctionne déjà sur le site que tu m'indiques (mais pas sur le site Pangloss v2) : souci d'intégration @EdouardSombie ?

- le contenu désiré n'est pas présent en tant que tel dans le XML. Dans ce cas, on concatène le contenu des balises correspondantes au niveau de la phrase : `<S>`
Pour ce texte, c'est ce qu'il faut faire pour la forme "phono". 
Actuellement, ça ne fonctionne pas.
(De mémoire, ça marche sur le site v1)

Encore un truc, qui a son importance : pourquoi l'option "phonetic" s'affiche-t-elle pour ce texte ? A ma connaissance, il n'y a aucun attribut `<FORM kindOf="phonetic">` dans le texte

Il faut prendre les attributs existants dans le texte et les afficher. Certains textes n'auront que ortho, d'autres que phono, d'autres rien du tout (aucun attribut explicite), d'autres des termes différents : "phonological", etc. Ce n'est pas un vocabulaire fermé (pour l'instant... et le 'refermer' / normaliser est une affaire d'années plutôt que de mois, étant donné la diversité des pratiques). 



@m8nli9ht On peut se parler qd tu veux entre 16h et 17h cet après-midi pour clarifier

Merci bcp

**Comment by m8nli9ht** [comment]
l'option de FORM "phonetic" a été ajoutée à la volée par mon parser de XML car des mots ont été transcrits (FORM) sans précision de type de transcription (kindOf). J'avais mis ce système en place afin de proposer une option "transcription" qui corresponde à autre chose qu'un type vide (ou null)

**Comment by alexis-michaud** [comment]
Il y a des cas dans lesquels le type de \<FORM\> n'est pas spécifié ; le spécifier comme "phonetic" peut être trompeur, mieux vaudrait ne rien afficher dans ce cas. 

C'est un cas qu'il faudrait traiter séparément des autres, dans l'affichage des options du lecteur. 
- Si on a le choix entre types de transcriptions : utiliser des boîtes, et tout est pour le mieux : 
![image](https://user-images.githubusercontent.com/6072524/99851630-a2606780-2b7f-11eb-8055-2ae3941a7914.png)
Même s'il n'y a qu'un type, on l'affiche, c'est très bien.
Une forme non spécifiée apparaîtrait alors comme "other" (s'il y a par exemple 1 forme orthographique encodée comme telle, et une autre forme non spécifiée).
- S'il n'y a qu'une seule sorte de transcription, de type non spécifié : au lieu du format ci-dessus, on aurait simplement une case à cocher face à la mention "Transcription" : 
![image](https://user-images.githubusercontent.com/6072524/99851803-0420d180-2b80-11eb-871e-4c9433177085.png)

**Comment by m8nli9ht** [comment]
J'ai modifié le parser de document pour afficher "other" quand le type n'est pas renseigné.
Par contre, proposer un affichage spécifique si une seule option est disponible ne me paraît pas du tout une bonne pratique d'un point de vue technique car il complexifie beaucoup le code : dans un cas "Transcriptions" est un libellé et "phono", "ortho"... sont les vraies options disponibles dans le document, dans l'autre cas "Transcriptions" devient une option qu'il va falloir gérer de façon spécifique car techniquement "Transcriptions" n'est pas un type de transcription (un kindOf dans le document) !!!

**Comment by alexis-michaud** [comment]
Excellent 👍
